// Generated by mono.tools/bindings. Do not edit by hand.
//
// What a TypeScript author can name, typed. TypeScript is the typed
// authoring surface over the JavaScript VM -- it erases its types by
// design, so this describes what the bindings expose and nothing about
// how a value is represented at run time.
//
// This is a type root: a `tsconfig.json` lists it in place of
// `@rbxts/types`. The one in the repository root already does, and
// `bunx tsc --noEmit` is what checks a script against it.
//
// Written alongside the Luau declarations by one program. Where the two
// disagree -- `game.GetService("Workspace")`, the `RunService`
// predicates -- they disagree because the two VMs do, and each file says
// what its own VM installs rather than what the other one has.

// --- the value types -------------------------------------------------------

declare interface Vector3 {
	readonly X: number;
	readonly Y: number;
	readonly Z: number;
	readonly Magnitude: number;
	readonly Unit: Vector3;
	add(other: Vector3): Vector3;
	sub(other: Vector3): Vector3;
	mul(other: Vector3 | number): Vector3;
	Equals(other: Vector3): boolean;
}

declare interface Color3 {
	readonly R: number;
	readonly G: number;
	readonly B: number;
	Equals(other: Color3): boolean;
}

declare interface CFrame {
	readonly Position: Vector3;
	mul(other: CFrame): CFrame;
}

declare const Vector3: {
	new: (x?: number, y?: number, z?: number) => Vector3;
};

declare const Color3: {
	new: (r?: number, g?: number, b?: number) => Color3;
	// 0-255, the way an author reads a colour off a palette.
	fromRGB: (r?: number, g?: number, b?: number) => Color3;
};

declare const CFrame: {
	new: {
		(x?: number, y?: number, z?: number): CFrame;
		(position: Vector3): CFrame;
	};
	// Radians, because Roblox's is radians -- while `Orientation` is degrees.
	Angles: (pitch: number, yaw: number, roll: number) => CFrame;
	lookAt: (from: Vector3, to: Vector3, up?: Vector3) => CFrame;
};

// --- signals ---------------------------------------------------------------
//
// `Heartbeat.Connect(fn)` rather than `Heartbeat:Connect(fn)` -- the colon is
// Lua's and a JavaScript author writes the dot. Same signal, same list.

declare interface RBXScriptConnection {
	readonly Connected: boolean;
	Disconnect(): void;
}

declare interface HeartbeatSignal {
	Connect(handler: (deltaTime: number) => void): RBXScriptConnection;
}

declare interface ChangedSignal {
	Connect(handler: (property: string) => void): RBXScriptConnection;
	Once(handler: (property: string) => void): RBXScriptConnection;
	Equals(other: ChangedSignal): boolean;
}

declare interface PropertyChangedSignal {
	Connect(handler: () => void): RBXScriptConnection;
	Once(handler: () => void): RBXScriptConnection;
	Equals(other: PropertyChangedSignal): boolean;
}

// --- queries ---------------------------------------------------------------

declare interface RaycastParams {
	CollisionGroup: string;
}

declare const RaycastParams: {
	new: () => RaycastParams;
};

declare interface RaycastResult {
	readonly Instance: Instance;
	readonly Position: Vector3;
	readonly Normal: Vector3;
	readonly Distance: number;
	readonly Material: Enum_Material;
}

declare interface EnumItem { readonly Name: string; readonly EnumType: string; Equals(other: EnumItem): boolean; }
declare interface Enum_EasingDirection extends EnumItem { readonly __enum: "EasingDirection"; }
declare interface Enum_EasingStyle extends EnumItem { readonly __enum: "EasingStyle"; }
declare interface Enum_Material extends EnumItem { readonly __enum: "Material"; }
declare interface Enum_NormalId extends EnumItem { readonly __enum: "NormalId"; }
declare interface Enum_ServiceScope extends EnumItem { readonly __enum: "ServiceScope"; }

declare namespace Enum {
	const EasingDirection: {
		readonly In: Enum_EasingDirection;
		readonly Out: Enum_EasingDirection;
		readonly InOut: Enum_EasingDirection;
	};
	const EasingStyle: {
		readonly Linear: Enum_EasingStyle;
		readonly Quad: Enum_EasingStyle;
		readonly Cubic: Enum_EasingStyle;
		readonly Quart: Enum_EasingStyle;
		readonly Quint: Enum_EasingStyle;
		readonly Sine: Enum_EasingStyle;
		readonly Exponential: Enum_EasingStyle;
		readonly Circular: Enum_EasingStyle;
		readonly Back: Enum_EasingStyle;
		readonly Elastic: Enum_EasingStyle;
		readonly Bounce: Enum_EasingStyle;
	};
	const Material: {
		readonly Plastic: Enum_Material;
		readonly SmoothPlastic: Enum_Material;
		readonly Wood: Enum_Material;
		readonly WoodPlanks: Enum_Material;
		readonly Metal: Enum_Material;
		readonly CorrodedMetal: Enum_Material;
		readonly DiamondPlate: Enum_Material;
		readonly Concrete: Enum_Material;
		readonly Brick: Enum_Material;
		readonly Cobblestone: Enum_Material;
		readonly Grass: Enum_Material;
		readonly Sand: Enum_Material;
		readonly Slate: Enum_Material;
		readonly Ice: Enum_Material;
		readonly Glass: Enum_Material;
		readonly Neon: Enum_Material;
		readonly ForceField: Enum_Material;
	};
	const NormalId: {
		readonly Right: Enum_NormalId;
		readonly Top: Enum_NormalId;
		readonly Back: Enum_NormalId;
		readonly Left: Enum_NormalId;
		readonly Bottom: Enum_NormalId;
		readonly Front: Enum_NormalId;
	};
	const ServiceScope: {
		readonly Shared: Enum_ServiceScope;
		readonly Server: Enum_ServiceScope;
		readonly Client: Enum_ServiceScope;
	};
}

// --- the datatype vocabulary ----------------------------------------------

declare interface Vector2 {
	readonly X: number;
	readonly Y: number;
	readonly Magnitude: number;
	readonly Unit: Vector2;
	add(other: Vector2): Vector2;
	sub(other: Vector2): Vector2;
	mul(other: Vector2 | number): Vector2;
	Equals(other: Vector2): boolean;
}

declare const Vector2: {
	new: (x?: number, y?: number) => Vector2;
};

declare interface UDim {
	readonly Scale: number;
	readonly Offset: number;
}

declare const UDim: {
	new: (scale?: number, offset?: number) => UDim;
};

declare interface UDim2 {
	readonly X: UDim;
	readonly Y: UDim;
}

declare const UDim2: {
	new: (xScale?: number, xOffset?: number, yScale?: number, yOffset?: number) => UDim2;
	// Four numbers where two are zero is noise an author stops reading.
	fromScale: (x?: number, y?: number) => UDim2;
	fromOffset: (x?: number, y?: number) => UDim2;
};

declare interface Rect {
	readonly Min: Vector2;
	readonly Max: Vector2;
	readonly Width: number;
	readonly Height: number;
}

declare const Rect: {
	new: {
		(min: Vector2, max: Vector2): Rect;
		(minX?: number, minY?: number, maxX?: number, maxY?: number): Rect;
	};
};

declare interface Region3 {
	readonly CFrame: CFrame;
	readonly Size: Vector3;
}

declare const Region3: {
	new: (min: Vector3, max: Vector3) => Region3;
};

declare interface NumberRange {
	readonly Min: number;
	readonly Max: number;
}

declare const NumberRange: {
	// One argument is the degenerate range, which is Roblox's shape.
	new: (min: number, max?: number) => NumberRange;
};

declare interface NumberSequence {
	Evaluate(time: number): number;
}

declare const NumberSequence: {
	new: {
		(value: number): NumberSequence;
		(from: number, to: number): NumberSequence;
		// `[time, value]`. The Luau half reads an envelope as a third element;
		// this one does not.
		(keypoints: [number, number][]): NumberSequence;
	};
};

declare interface ColorSequence {
	Evaluate(time: number): Color3;
}

declare const ColorSequence: {
	new: {
		(value: Color3): ColorSequence;
		(from: Color3, to: Color3): ColorSequence;
	};
};

declare interface TweenInfo {
	readonly Time: number;
	readonly DelayTime: number;
	readonly RepeatCount: number;
	readonly Reverses: boolean;
	Evaluate(time: number): number;
}

declare const TweenInfo: {
	new: (
		time?: number,
		style?: Enum_EasingStyle,
		direction?: Enum_EasingDirection,
		repeatCount?: number,
		reverses?: boolean,
		delayTime?: number
	) => TweenInfo;
};

// The direction is normalised on the way in, so the length an author passed is
// not silently kept.
declare interface Ray {
	readonly Origin: Vector3;
	readonly Direction: Vector3;
	PointAt(distance: number): Vector3;
}

declare const Ray: {
	new: (origin: Vector3, direction: Vector3) => Ray;
};

// Indexed rather than streamed underneath: the seed is a salt and the draw
// number is an index, so a script's sequence is a pure function of its seed and
// how many values it has taken. Two runs agree and a recording replays.
declare interface Random {
	NextNumber(min?: number, max?: number): number;
	// Inclusive of both ends, which is Roblox's contract.
	NextInteger(min: number, max: number): number;
}

declare const Random: {
	new: (seed?: number) => Random;
};

declare interface DateTime {
	readonly UnixTimestamp: number;
	readonly UnixTimestampMillis: number;
}

declare const DateTime: {
	// **Always throws**, hence `never`, and the refusal is the design: a world's
	// clock is simulated, and a script branching on wall time produces a run
	// that does not replay. The two below are what to use instead.
	now: () => never;
	fromSimulated: () => DateTime;
	fromUnixTimestamp: (seconds: number) => DateTime;
};

// --- the class tree -------------------------------------------------------

declare interface Instance {
	Name: string;
	Parent: Instance;
	readonly Changed: ChangedSignal;
	IsA(className: string): boolean;
	Destroy(): void;
	Clone(): Instance;
	GetChildren(): Instance[];
	GetDescendants(): Instance[];
	FindFirstChild(name: string): Instance | null;
	IsDescendantOf(ancestor: Instance): boolean;
	ClearAllChildren(): void;
	GetPropertyChangedSignal(property: string): PropertyChangedSignal;
}

declare interface PVInstance extends Instance {
	CFrame: CFrame;
	Orientation: Vector3;
	Position: Vector3;
}

declare interface BasePart extends PVInstance {
	Anchored: boolean;
	CanCollide: boolean;
	CastShadow: boolean;
	CollisionGroup: string;
	Color: Color3;
	Material: Enum_Material;
	Mesh: string;
	Size: Vector3;
	Transparency: number;
	Visible: boolean;
}

declare interface Part extends BasePart {
}

declare interface Camera extends PVInstance {
	FarPlaneZ: number;
	FieldOfView: number;
	NearPlaneZ: number;
	SurfaceSize: Vector3;
}

declare interface SurfaceCamera extends Camera {
	Face: Enum_NormalId;
	ImageTransparency: number;
}

declare interface LuaSourceContainer extends Instance {
	Disabled: boolean;
	Source: string;
}

declare interface Script extends LuaSourceContainer {
}

declare interface LocalScript extends LuaSourceContainer {
}

declare interface Service extends Instance {
	Fixture: boolean;
	Scope: Enum_ServiceScope;
}

declare interface Workspace extends Service {
	CurrentCamera: Camera | null;
	Raycast(origin: Vector3, direction: Vector3, params?: RaycastParams): RaycastResult | null;
}

declare interface Lighting extends Service {
	Ambient: Color3;
	Brightness: number;
	ClockTime: number;
	FogColor: Color3;
	FogEnd: number;
	FogStart: number;
	GeographicLatitude: number;
	OutdoorAmbient: Color3;
}

declare interface ReplicatedFirst extends Service {
}

declare interface ReplicatedStorage extends Service {
}

declare interface ServerScriptService extends Service {
}

declare interface ServerStorage extends Service {
}

declare interface StarterGui extends Service {
}

declare interface StarterPlayer extends Service {
}

declare interface StarterPlayerScripts extends Service {
}

// --- the bus services ------------------------------------------------------

declare type BusStatus =
	| "Ok"
	| "NotFound"
	| "Conflict"
	| "OverBudget"
	| "NoSuchWorld"
	| "Unsupported"
	| "Unknown";

declare interface StoreReply {
	readonly Value: unknown;
	readonly Status: BusStatus;
	readonly Version: number;
}

declare interface MessagingService {
	PublishAsync(topic: string, message: unknown): Promise<StoreReply>;
	SubscribeAsync(topic: string, handler: (message: unknown) => void): void;
}

declare interface MemoryStoreService {
	GetAsync(key: string): Promise<StoreReply>;
	SetAsync(key: string, value: unknown): Promise<StoreReply>;
	UpdateAsync(key: string, version: number, value: unknown): Promise<StoreReply>;
	RemoveAsync(key: string): Promise<StoreReply>;
}

declare interface DataStoreService {
	GetAsync(key: string): Promise<StoreReply>;
	SetAsync(key: string, value: unknown): Promise<StoreReply>;
	RemoveAsync(key: string): Promise<StoreReply>;
}

declare interface RunService {
	readonly Heartbeat: HeartbeatSignal;
}

// --- the globals -----------------------------------------------------------

declare const MessagingService: MessagingService;
declare const MemoryStoreService: MemoryStoreService;
declare const DataStoreService: DataStoreService;
declare const RunService: RunService;

// The world this script runs on. `game` is the universe above it.
declare const workspace: Workspace;

// An alias for `null`, because this is a Roblox-shaped API and a Roblox author
// writes `part.Parent = nil`. A third empty value would be a footgun wearing a
// familiar name, so it is not one.
declare const nil: null;

declare function print(...values: unknown[]): void;
declare function warn(...values: unknown[]): void;
declare function typeOf(value: unknown): string;
declare function time(): number;
declare function tick(): number;

declare const task: {
	wait: (seconds?: number) => number;
	spawn: (callback: (...args: unknown[]) => void, ...args: unknown[]) => void;
	defer: (callback: (...args: unknown[]) => void, ...args: unknown[]) => void;
	delay: (seconds: number, callback: (...args: unknown[]) => void) => void;
	cancel: (handle: unknown) => void;
};

declare const game: {
	GetService: {
		(service: "RunService"): RunService;
		(service: "MessagingService"): MessagingService;
		(service: "MemoryStoreService"): MemoryStoreService;
		(service: "DataStoreService"): DataStoreService;
	};
};

declare const Instance: {
	new: {
		(className: "Instance", parent?: Instance): Instance;
		(className: "PVInstance", parent?: Instance): PVInstance;
		(className: "BasePart", parent?: Instance): BasePart;
		(className: "Part", parent?: Instance): Part;
		(className: "Camera", parent?: Instance): Camera;
		(className: "SurfaceCamera", parent?: Instance): SurfaceCamera;
		(className: "LuaSourceContainer", parent?: Instance): LuaSourceContainer;
		(className: "Script", parent?: Instance): Script;
		(className: "LocalScript", parent?: Instance): LocalScript;
	};
};
