// Generated by mono.tools/bindings. Do not edit by hand.
//
// What a TypeScript author can name, typed. TypeScript is the typed
// authoring surface over the JavaScript VM -- it erases its types by
// design, so this describes what the bindings expose and nothing about
// how a value is represented at run time.

declare interface Vector3 { readonly X: number; readonly Y: number; readonly Z: number; }
declare interface Color3 { readonly R: number; readonly G: number; readonly B: number; }
declare interface CFrame { readonly Position: Vector3; }

declare const Vector3: { new(x?: number, y?: number, z?: number): Vector3 };
declare const Color3: { new(r?: number, g?: number, b?: number): Color3 };
declare function print(...values: unknown[]): void;

declare interface EnumItem { readonly Name: string; readonly EnumType: string; Equals(other: EnumItem): boolean; }
declare interface Enum_Material extends EnumItem { readonly __enum: "Material"; }
declare interface Enum_NormalId extends EnumItem { readonly __enum: "NormalId"; }

declare namespace Enum {
	const Material: {
		readonly Plastic: Enum_Material;
		readonly SmoothPlastic: Enum_Material;
		readonly Wood: Enum_Material;
		readonly WoodPlanks: Enum_Material;
		readonly Metal: Enum_Material;
		readonly CorrodedMetal: Enum_Material;
		readonly DiamondPlate: Enum_Material;
		readonly Concrete: Enum_Material;
		readonly Brick: Enum_Material;
		readonly Cobblestone: Enum_Material;
		readonly Grass: Enum_Material;
		readonly Sand: Enum_Material;
		readonly Slate: Enum_Material;
		readonly Ice: Enum_Material;
		readonly Glass: Enum_Material;
		readonly Neon: Enum_Material;
		readonly ForceField: Enum_Material;
	};
	const NormalId: {
		readonly Right: Enum_NormalId;
		readonly Top: Enum_NormalId;
		readonly Back: Enum_NormalId;
		readonly Left: Enum_NormalId;
		readonly Bottom: Enum_NormalId;
		readonly Front: Enum_NormalId;
	};
}

declare interface Instance {
	Name: string;
	Parent: Instance;
}

declare interface PVInstance extends Instance {
	CFrame: CFrame;
	Orientation: Vector3;
	Position: Vector3;
}

declare interface BasePart extends PVInstance {
	Anchored: boolean;
	CanCollide: boolean;
	CastShadow: boolean;
	CollisionGroup: string;
	Color: Color3;
	Material: Enum_Material;
	Mesh: string;
	Size: Vector3;
	Surface: number;
	Transparency: number;
	Visible: boolean;
}

declare interface Part extends BasePart {
}

declare interface Camera extends PVInstance {
	FarPlaneZ: number;
	FieldOfView: number;
	NearPlaneZ: number;
	SurfaceSize: Vector3;
}

declare interface SurfaceCamera extends Camera {
	Face: Enum_NormalId;
	ImageTransparency: number;
}

declare interface LuaSourceContainer extends Instance {
	Disabled: boolean;
	Source: string;
}

declare interface Script extends LuaSourceContainer {
}

declare interface LocalScript extends LuaSourceContainer {
}

declare const Instance: {
	new(className: "Instance"): Instance;
	new(className: "PVInstance"): PVInstance;
	new(className: "BasePart"): BasePart;
	new(className: "Part"): Part;
	new(className: "Camera"): Camera;
	new(className: "SurfaceCamera"): SurfaceCamera;
	new(className: "LuaSourceContainer"): LuaSourceContainer;
	new(className: "Script"): Script;
	new(className: "LocalScript"): LocalScript;
};
