file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(capture "${OUTPUT_DIR}/observed.rng")
function(prepare destination first second expected)
	execute_process(COMMAND "${ASSETC}" --export-graph "${INPUT}" --prepare-builtin-random palette
		--builtin-random-output "${destination}" --builtin-random-draw "${first}" --builtin-random-draw "${second}"
		RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
	if(NOT status EQUAL expected)
		message(FATAL_ERROR "Capture preparation expected ${expected}, got ${status}: ${output}${error}")
	endif()
endfunction()
prepare("${capture}" "random:0:1:0.1" "random:0:1:0.9" 0)
file(SHA256 "${capture}" capture_hash)
prepare("${capture}" "unknown:0:1:0.1" "random:0:1:0.9" 2)
file(SHA256 "${capture}" rejected_hash)
if(NOT capture_hash STREQUAL rejected_hash)
	message(FATAL_ERROR "Invalid named observation changed the prior recording")
endif()
function(render tool destination recording expected)
	if(tool STREQUAL "assetc")
		set(command "${ASSETC}" --export-graph "${INPUT}" --graph-output image --output "${destination}")
	else()
		set(command "${IMAGEGRAPH}" --input "${INPUT}" --output-id image --output "${destination}")
	endif()
	if(NOT recording STREQUAL "")
		list(APPEND command --builtin-random-capture "${recording}")
	endif()
	execute_process(COMMAND ${command} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
	if(NOT status EQUAL expected)
		message(FATAL_ERROR "${tool} replay expected ${expected}, got ${status}: ${output}${error}")
	endif()
endfunction()
render(assetc "${OUTPUT_DIR}/first.png" "${capture}" 0)
render(imagegraph "${OUTPUT_DIR}/repeat.png" "${capture}" 0)
file(READ "${OUTPUT_DIR}/first.png" dimensions OFFSET 16 LIMIT 8 HEX)
if(NOT dimensions STREQUAL "0000000800000008")
	message(FATAL_ERROR "Recorded RNG graph did not produce an 8x8 PNG")
endif()
file(SHA256 "${OUTPUT_DIR}/first.png" first_hash)
file(SHA256 "${OUTPUT_DIR}/repeat.png" repeat_hash)
if(NOT first_hash STREQUAL repeat_hash)
	message(FATAL_ERROR "assetc and shared runner disagreed on immutable RNG observations")
endif()
render(assetc "${OUTPUT_DIR}/first.png" "" 1)
file(SHA256 "${OUTPUT_DIR}/first.png" retained_hash)
if(NOT first_hash STREQUAL retained_hash)
	message(FATAL_ERROR "Missing source observations changed previous pixels")
endif()
# Source representatives are sorted by palette index; swapping centres alone preserves the output.
prepare("${OUTPUT_DIR}/different.rng" "random:0:1:0.6" "random:0:1:0.9" 0)
render(assetc "${OUTPUT_DIR}/different.png" "${OUTPUT_DIR}/different.rng" 0)
file(SHA256 "${OUTPUT_DIR}/different.png" different_hash)
if(first_hash STREQUAL different_hash)
	message(FATAL_ERROR "Different supplied cluster observations failed to change output pixels")
endif()
prepare("${OUTPUT_DIR}/wrong-call.rng" "random:0:2:0.1" "random:0:1:0.9" 0)
render(assetc "${OUTPUT_DIR}/first.png" "${OUTPUT_DIR}/wrong-call.rng" 1)
file(SHA256 "${OUTPUT_DIR}/first.png" retained_hash)
if(NOT first_hash STREQUAL retained_hash)
	message(FATAL_ERROR "Wrong source call bounds changed previous pixels")
endif()
file(WRITE "${OUTPUT_DIR}/malformed.rng" "not a builtin random capture\n")
render(assetc "${OUTPUT_DIR}/first.png" "${OUTPUT_DIR}/malformed.rng" 1)
file(SHA256 "${OUTPUT_DIR}/first.png" retained_hash)
if(NOT first_hash STREQUAL retained_hash)
	message(FATAL_ERROR "Malformed recording changed previous pixels")
endif()
execute_process(COMMAND "${ASSETC}" --input "${OUTPUT_DIR}" --output "${OUTPUT_DIR}/rejected"
	--builtin-random-capture "${capture}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
if(NOT status EQUAL 2 OR NOT error MATCHES "require --export-graph" OR EXISTS "${OUTPUT_DIR}/rejected")
	message(FATAL_ERROR "Tree baking silently accepted RNG replay inputs: ${output}${error}")
endif()
file(WRITE "${OUTPUT_DIR}/future.rng" "imagegraph-builtin-random 99\n0\n")
render(assetc "${OUTPUT_DIR}/first.png" "${OUTPUT_DIR}/future.rng" 1)
file(SHA256 "${OUTPUT_DIR}/first.png" retained_hash)
if(NOT first_hash STREQUAL retained_hash)
	message(FATAL_ERROR "Unsupported recording version changed previous pixels")
endif()
execute_process(COMMAND "${ASSETC}" --export-graph "${INPUT}" --graph-output image
	--output "${OUTPUT_DIR}/first.png" --graph-tick 1 --builtin-random-capture "${capture}"
	RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
file(SHA256 "${OUTPUT_DIR}/first.png" retained_hash)
if(NOT status EQUAL 1 OR NOT first_hash STREQUAL retained_hash)
	message(FATAL_ERROR "Stale time recording did not reject atomically: ${output}${error}")
endif()
