file(MAKE_DIRECTORY "${OUTPUT_DIR}")
function(render tool name tick playing)
	set(destination "${OUTPUT_DIR}/${name}.png")
	if(tool STREQUAL "assetc")
		set(command "${ASSETC}" --export-graph "${INPUT}" --graph-output image --output "${destination}" --graph-tick "${tick}")
	else()
		set(command "${IMAGEGRAPH}" --input "${INPUT}" --output-id image --output "${destination}" --tick "${tick}")
	endif()
	if(playing)
		list(APPEND command --rigid-playing --rigid-frame-progress)
	endif()
	execute_process(COMMAND ${command} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
	if(NOT status EQUAL 0)
		message(FATAL_ERROR "${name} rigid CLI export failed: ${output}${error}")
	endif()
	file(READ "${destination}" dimensions OFFSET 16 LIMIT 8 HEX)
	if(NOT dimensions STREQUAL "0000002000000020")
		message(FATAL_ERROR "${name} did not export a 32x32 PNG")
	endif()
	file(SHA256 "${destination}" hash)
	set("${name}_hash" "${hash}" PARENT_SCOPE)
endfunction()
render(assetc paused 0 FALSE)
render(assetc first 0 TRUE)
render(assetc later 12 TRUE)
render(assetc repeat 12 TRUE)
render(assetc seek 0 TRUE)
render(imagegraph runner_first 0 TRUE)
render(imagegraph runner_later 12 TRUE)
if(paused_hash STREQUAL first_hash OR first_hash STREQUAL later_hash)
	message(FATAL_ERROR "source playback flags did not distinguish paused and moving rigid actors")
endif()
if(NOT later_hash STREQUAL repeat_hash OR NOT first_hash STREQUAL seek_hash)
	message(FATAL_ERROR "rigid CLI repeated frame or backward seek changed deterministic PNG bytes")
endif()
if(NOT first_hash STREQUAL runner_first_hash OR NOT later_hash STREQUAL runner_later_hash)
	message(FATAL_ERROR "assetc and imagegraph disagreed on source rigid observations")
endif()

foreach(flag IN ITEMS --rigid-playing --rigid-frame-progress)
	execute_process(
		COMMAND "${ASSETC}" --input "${OUTPUT_DIR}/unused-input" --output "${OUTPUT_DIR}/rejected" "${flag}"
		RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
	if(NOT status EQUAL 2 OR NOT error MATCHES "require --export-graph")
		message(FATAL_ERROR "assetc silently accepted unsupported tree-bake rigid flag ${flag}: ${status}: ${output}${error}")
	endif()
	if(EXISTS "${OUTPUT_DIR}/rejected")
		message(FATAL_ERROR "assetc created tree-bake output before rejecting ${flag}")
	endif()
endforeach()
