file(MAKE_DIRECTORY "${OUTPUT_DIR}")
function(render tool name width)
	set(destination "${OUTPUT_DIR}/${name}.png")
	if(tool STREQUAL "assetc")
		set(command "${ASSETC}" --export-graph "${INPUT}" --graph-output image --output "${destination}")
	else()
		set(command "${IMAGEGRAPH}" --input "${INPUT}" --output-id image --output "${destination}")
	endif()
	if(NOT width EQUAL 2)
		list(APPEND command --graph-argument-integer "width=${width}")
	endif()
	execute_process(COMMAND ${command} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
	if(NOT status EQUAL 0)
		message(FATAL_ERROR "${name} argument export failed: ${status}: ${output}${error}")
	endif()
	file(READ "${destination}" dimension OFFSET 16 LIMIT 8 HEX)
	if(width EQUAL 2)
		set(expected "0000000200000001")
	else()
		set(expected "0000000300000001")
	endif()
	if(NOT dimension STREQUAL expected)
		message(FATAL_ERROR "${name} did not publish expected argument dimensions: ${dimension}")
	endif()
	file(SHA256 "${destination}" hash)
	set("${name}_hash" "${hash}" PARENT_SCOPE)
endfunction()
render(assetc default 2)
render(assetc assigned 3)
render(imagegraph runner_default 2)
render(imagegraph runner_assigned 3)
if(NOT default_hash STREQUAL runner_default_hash OR NOT assigned_hash STREQUAL runner_assigned_hash)
	message(FATAL_ERROR "assetc and runner argument observations changed pixels")
endif()
if(default_hash STREQUAL assigned_hash)
	message(FATAL_ERROR "typed graph argument did not change the rendered image")
endif()
execute_process(COMMAND "${ASSETC}" --export-graph "${INPUT}" --graph-output image
	--output "${OUTPUT_DIR}/assigned.png" --graph-argument width=9 --graph-argument-bool width=false
	RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
set(diagnostic "${output}${error}")
if(NOT status EQUAL 2 OR NOT diagnostic MATCHES "repeats a name")
	message(FATAL_ERROR "assetc did not refuse duplicate argument names: ${status}: ${output}${error}")
endif()
file(SHA256 "${OUTPUT_DIR}/assigned.png" preserved_hash)
if(NOT assigned_hash STREQUAL preserved_hash)
	message(FATAL_ERROR "failed argument preparation changed prior export")
endif()
