#include <engine/core/Bytes.hpp>
#include <engine/ecs/Components.hpp>
#include <engine/gui/Components.hpp>
#include <engine/gui/Registration.hpp>
#include <engine/gui/SettingsMenu.hpp>

#include <array>
#include <cstddef>
#include <cstdint>

namespace engine::gui {

	namespace {
		// Three components hold a `core::Name`, and a name's id is a counter
		// this process assigned in first-seen order. The generated byte
		// serialiser would write that counter, and a reading process would
		// resolve it to whatever string happened to take the same number -
		// which is not a corrupt file, it is a file that loads and is wrong.
		//
		// `scene`'s `WriteVisuals` says the same thing and carries the lesson
		// this repeats deliberately: **a field added to a type with a
		// hand-written serialiser crosses only if somebody remembers, and
		// nothing in the build checks.** So each pair below writes every field
		// of its struct in declaration order, and `gui/tests/Registration.cpp`
		// round-trips a fully-populated value rather than a default one - a
		// default-valued round trip passes whatever you forget.

		void WriteLabels(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *labels = static_cast<const Label *>(source);
			for (size_t index = 0; index < count; index++) {
				const Label &label = labels[index];
				writer.WriteString(label.Text);
				writer.WriteFloat(label.Color.R);
				writer.WriteFloat(label.Color.G);
				writer.WriteFloat(label.Color.B);
				writer.WriteFloat(label.Transparency);
				writer.WriteInt32(label.Size);
				writer.WriteInt8(static_cast<int8_t>(label.Font));
				writer.WriteInt8(static_cast<int8_t>(label.XAlignment));
				writer.WriteInt8(static_cast<int8_t>(label.YAlignment));
				writer.WriteBool(label.Wrapped);
				writer.WriteBool(label.Scaled);
				writer.WriteInt8(static_cast<int8_t>(label.Truncate));
				writer.WriteFloat(label.StrokeColor.R);
				writer.WriteFloat(label.StrokeColor.G);
				writer.WriteFloat(label.StrokeColor.B);
				writer.WriteFloat(label.StrokeTransparency);
				writer.WriteFloat(label.LineHeight);

				// **Added at v0.18, in the same breath as the fields.** This
				// pair is exactly the discipline the comment above this function
				// exists to keep, and the reason it is written down twice.
				writer.WriteInt32(label.MaxVisible);
				writer.WriteBool(label.Rich);
			}
		}

		void ReadLabels(core::ByteReader &reader, void *destination, size_t count) {
			auto *labels = static_cast<Label *>(destination);
			for (size_t index = 0; index < count; index++) {
				Label &label = labels[index];
				label.Text = std::string(reader.ReadString());
				label.Color.R = reader.ReadFloat();
				label.Color.G = reader.ReadFloat();
				label.Color.B = reader.ReadFloat();
				label.Transparency = reader.ReadFloat();
				label.Size = reader.ReadInt32();
				label.Font = static_cast<FontFace>(reader.ReadInt8());
				label.XAlignment = static_cast<TextXAlignment>(reader.ReadInt8());
				label.YAlignment = static_cast<TextYAlignment>(reader.ReadInt8());
				label.Wrapped = reader.ReadBool();
				label.Scaled = reader.ReadBool();
				label.Truncate = static_cast<TextTruncate>(reader.ReadInt8());
				label.StrokeColor.R = reader.ReadFloat();
				label.StrokeColor.G = reader.ReadFloat();
				label.StrokeColor.B = reader.ReadFloat();
				label.StrokeTransparency = reader.ReadFloat();
				label.LineHeight = reader.ReadFloat();
				label.MaxVisible = reader.ReadInt32();
				label.Rich = reader.ReadBool();
			}
		}

		// **`gui.Gradient` is here for a different reason from the three above,
		// and it is a size rather than a correctness one.**
		//
		// A `core::ColorSequence` is twenty keypoint slots and a count, and a
		// `core::NumberSequence` is twenty more - 656 of the component's 672
		// bytes. The generated writer copies the object representation, so every
		// gradient in every world wrote all forty slots into every save and
		// every replication delta, whatever `Count` said. **A default two-stop
		// gradient is thirty-two meaningful bytes of ramp**, and it was costing
		// 656.
		//
		// So this writes `Count` and then that many stops, exactly as
		// `effects`'s ribbon pair does for the same two types. `Sequence::Add`
		// on the way back in is what keeps a hostile file from claiming a count
		// past the capacity.
		void WriteRamp(core::ByteWriter &writer, const core::ColorSequence &sequence) {
			writer.WriteUInt32(sequence.Count);
			for (uint32_t stop = 0; stop < sequence.Count; stop++) {
				writer.WriteFloat(sequence.Keypoints[stop].Time);
				writer.WriteFloat(sequence.Keypoints[stop].Value.R);
				writer.WriteFloat(sequence.Keypoints[stop].Value.G);
				writer.WriteFloat(sequence.Keypoints[stop].Value.B);
			}
		}

		void ReadRamp(core::ByteReader &reader, core::ColorSequence &sequence) {
			sequence = core::ColorSequence{};
			const uint32_t stops = reader.ReadUInt32();
			for (uint32_t stop = 0; stop < stops && !reader.Failed(); stop++) {
				const float at = reader.ReadFloat();
				const float red = reader.ReadFloat();
				const float green = reader.ReadFloat();
				const float blue = reader.ReadFloat();
				(void)sequence.Add(core::ColorKeypoint{at, core::Color3{red, green, blue}});
			}
		}

		void WriteCurve(core::ByteWriter &writer, const core::NumberSequence &sequence) {
			writer.WriteUInt32(sequence.Count);
			for (uint32_t stop = 0; stop < sequence.Count; stop++) {
				writer.WriteFloat(sequence.Keypoints[stop].Time);
				writer.WriteFloat(sequence.Keypoints[stop].Value);
				writer.WriteFloat(sequence.Keypoints[stop].Envelope);
			}
		}

		void ReadCurve(core::ByteReader &reader, core::NumberSequence &sequence) {
			sequence = core::NumberSequence{};
			const uint32_t stops = reader.ReadUInt32();
			for (uint32_t stop = 0; stop < stops && !reader.Failed(); stop++) {
				const float at = reader.ReadFloat();
				const float value = reader.ReadFloat();
				const float envelope = reader.ReadFloat();
				(void)sequence.Add(core::NumberKeypoint{at, value, envelope});
			}
		}

		void WriteGradients(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *gradients = static_cast<const Gradient *>(source);
			for (size_t index = 0; index < count; index++) {
				const Gradient &gradient = gradients[index];
				WriteRamp(writer, gradient.Color);
				WriteCurve(writer, gradient.Transparency);
				writer.WriteFloat(gradient.Offset.X);
				writer.WriteFloat(gradient.Offset.Y);
				writer.WriteFloat(gradient.Rotation);
				writer.WriteBool(gradient.Enabled);
			}
		}

		void ReadGradients(core::ByteReader &reader, void *destination, size_t count) {
			auto *gradients = static_cast<Gradient *>(destination);
			for (size_t index = 0; index < count; index++) {
				Gradient &gradient = gradients[index];
				ReadRamp(reader, gradient.Color);
				ReadCurve(reader, gradient.Transparency);
				gradient.Offset.X = reader.ReadFloat();
				gradient.Offset.Y = reader.ReadFloat();
				gradient.Rotation = reader.ReadFloat();
				gradient.Enabled = reader.ReadBool();
			}
		}

		void WritePictures(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *pictures = static_cast<const Picture *>(source);
			for (size_t index = 0; index < count; index++) {
				const Picture &picture = pictures[index];
				writer.WriteName(picture.Image);
				writer.WriteFloat(picture.Color.R);
				writer.WriteFloat(picture.Color.G);
				writer.WriteFloat(picture.Color.B);
				writer.WriteFloat(picture.Transparency);
				writer.WriteInt8(static_cast<int8_t>(picture.Scale));
				writer.WriteFloat(picture.SliceCenter.Min.X);
				writer.WriteFloat(picture.SliceCenter.Min.Y);
				writer.WriteFloat(picture.SliceCenter.Max.X);
				writer.WriteFloat(picture.SliceCenter.Max.Y);
				writer.WriteFloat(picture.SliceScale);
				writer.WriteFloat(picture.TileSize.X.Scale);
				writer.WriteFloat(picture.TileSize.X.Offset);
				writer.WriteFloat(picture.TileSize.Y.Scale);
				writer.WriteFloat(picture.TileSize.Y.Offset);
				writer.WriteFloat(picture.RectOffset.X);
				writer.WriteFloat(picture.RectOffset.Y);
				writer.WriteFloat(picture.RectSize.X);
				writer.WriteFloat(picture.RectSize.Y);

				// **Added at v0.18, in the same breath as the field - see
				// `WriteVisuals`' own comment for what happens when that
				// discipline slips.**
				writer.WriteName(picture.Shader);

				// **Added at v0.18, in the same breath as the fields**, which is
				// the discipline the comment above exists to keep.
				writer.WriteName(picture.HoverImage);
				writer.WriteName(picture.PressedImage);
				writer.WriteInt8(static_cast<int8_t>(picture.Resample));
			}
		}

		void ReadPictures(core::ByteReader &reader, void *destination, size_t count) {
			auto *pictures = static_cast<Picture *>(destination);
			for (size_t index = 0; index < count; index++) {
				Picture &picture = pictures[index];
				picture.Image = reader.ReadName();
				picture.Color.R = reader.ReadFloat();
				picture.Color.G = reader.ReadFloat();
				picture.Color.B = reader.ReadFloat();
				picture.Transparency = reader.ReadFloat();
				picture.Scale = static_cast<ScaleType>(reader.ReadInt8());
				picture.SliceCenter.Min.X = reader.ReadFloat();
				picture.SliceCenter.Min.Y = reader.ReadFloat();
				picture.SliceCenter.Max.X = reader.ReadFloat();
				picture.SliceCenter.Max.Y = reader.ReadFloat();
				picture.SliceScale = reader.ReadFloat();
				picture.TileSize.X.Scale = reader.ReadFloat();
				picture.TileSize.X.Offset = reader.ReadFloat();
				picture.TileSize.Y.Scale = reader.ReadFloat();
				picture.TileSize.Y.Offset = reader.ReadFloat();
				picture.RectOffset.X = reader.ReadFloat();
				picture.RectOffset.Y = reader.ReadFloat();
				picture.RectSize.X = reader.ReadFloat();
				picture.RectSize.Y = reader.ReadFloat();
				picture.Shader = reader.ReadName();
				picture.HoverImage = reader.ReadName();
				picture.PressedImage = reader.ReadName();
				picture.Resample = static_cast<ResampleMode>(reader.ReadInt8());
			}
		}

		void WriteEntries(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *entries = static_cast<const Entry *>(source);
			for (size_t index = 0; index < count; index++) {
				const Entry &entry = entries[index];
				writer.WriteString(entry.PlaceholderText);
				writer.WriteFloat(entry.PlaceholderColor.R);
				writer.WriteFloat(entry.PlaceholderColor.G);
				writer.WriteFloat(entry.PlaceholderColor.B);
				writer.WriteBool(entry.ClearTextOnFocus);
				writer.WriteBool(entry.MultiLine);
				writer.WriteBool(entry.TextEditable);

				// **The caret is not written and reads back as unfocused.** It
				// is where somebody's cursor is, which is not a fact about the
				// game - a save file that restored a text box mid-edit would be
				// restoring a session rather than a scene, and a *replica* that
				// received one would move the local player's caret.
				writer.WriteInt32(-1);
				writer.WriteInt32(-1);
			}
		}

		void ReadEntries(core::ByteReader &reader, void *destination, size_t count) {
			auto *entries = static_cast<Entry *>(destination);
			for (size_t index = 0; index < count; index++) {
				Entry &entry = entries[index];
				entry.PlaceholderText = std::string(reader.ReadString());
				entry.PlaceholderColor.R = reader.ReadFloat();
				entry.PlaceholderColor.G = reader.ReadFloat();
				entry.PlaceholderColor.B = reader.ReadFloat();
				entry.ClearTextOnFocus = reader.ReadBool();
				entry.MultiLine = reader.ReadBool();
				entry.TextEditable = reader.ReadBool();
				entry.CursorPosition = reader.ReadInt32();
				entry.SelectionStart = reader.ReadInt32();
			}
		}
	}

	void RegisterGuiComponents() {
		// Order is deliberate and not alphabetical, exactly as `scene`'s list
		// is: it decides component ids, which decide the order archetypes
		// iterate their columns in. **Add at the end.**
		//
		// The authored ones first, then the modifiers, then the one derived
		// component - which puts `Resolved` last, where a reader looking for
		// "what does the layout write" finds it without reading the rest.
		ecs::Components::Register<Element>("gui.Element");
		ecs::Components::Register<Background>("gui.Background");
		ecs::Components::Register<Label>("gui.Label", WriteLabels, ReadLabels);
		ecs::Components::Register<Picture>("gui.Picture", WritePictures, ReadPictures);
		ecs::Components::Register<Button>("gui.Button");
		ecs::Components::Register<Scrolling>("gui.Scrolling");
		ecs::Components::Register<Entry>("gui.Entry", WriteEntries, ReadEntries);
		ecs::Components::Register<Layer>("gui.Layer");
		ecs::Components::Register<Canvas>("gui.Canvas");
		ecs::Components::Register<Surface>("gui.Surface");
		ecs::Components::Register<Billboard>("gui.Billboard");
		ecs::Components::Register<Group>("gui.Group");
		ecs::Components::Register<Viewport>("gui.Viewport");

		ecs::Components::Register<Padding>("gui.Padding");
		ecs::Components::Register<ListLayout>("gui.ListLayout");
		ecs::Components::Register<GridLayout>("gui.GridLayout");
		ecs::Components::Register<AspectRatio>("gui.AspectRatio");
		ecs::Components::Register<SizeLimits>("gui.SizeLimits");
		ecs::Components::Register<TextSizeLimits>("gui.TextSizeLimits");
		ecs::Components::Register<Corner>("gui.Corner");
		ecs::Components::Register<Stroke>("gui.Stroke");
		ecs::Components::Register<Scale>("gui.Scale");

		// **Derived, and it still has a stable registered name.** It is written
		// every frame by the layout pass and nothing replicates it - the
		// authority and the replica derive it identically from the same tree,
		// which is `scene::Visibility`'s argument - but a component with only
		// the automatic name `Components::Of<T>` mints from the compiler's
		// spelling is one two processes cannot agree on, and a snapshot taken
		// in a studio and restored in a test would be one of those two.
		ecs::Components::Register<Resolved>("gui.Resolved");

		// **Derived too, and at the end for the reason the block below repeats.**
		// Written by whoever holds a camera and a world - `render` today - and
		// read by `CanvasFor`. A world that nobody draws never gets one, which is
		// exactly the case the authored fallback is for.
		ecs::Components::Register<SpatialCanvas>("gui.SpatialCanvas");

		// **After `Resolved`, because the rule above is "add at the end".** The
		// order decides component ids, which decide the column order an
		// archetype iterates - so inserting this among the authored ones to keep
		// the grouping tidy would renumber everything after it and change what a
		// recording made before this version means.
		//
		// It carries an `ecs::Entity`, which crosses as an id and a generation
		// and needs no hand-written serialiser: unlike a `core::Name`, an entity
		// id means the same thing in the file it was written from and the world
		// it is read into, because that is what `ecs::Store::Load` remaps.
		ecs::Components::Register<GuiServiceState>("gui.GuiServiceState");

		// The 3D branch, at the end for the reason the rule above gives.
		ecs::Components::Register<Adornment>("gui.Adornment");
		ecs::Components::Register<SelectionOutline>("gui.SelectionOutline");
		ecs::Components::Register<HandleShape>("gui.HandleShape");

		// A modifier by nature, and still registered after the 3D branch:
		// the list is append-only because ids decide archetype column order,
		// so arriving at v0.17 puts it here rather than beside `Scale`.
		ecs::Components::Register<FlexItem>("gui.FlexItem");

		// Append-only, for the reason above. Trivially copyable despite holding
		// two sequences - `core::Sequence` is fixed-capacity precisely so that a
		// ramp can be a component, and its own header carries the argument.
		ecs::Components::Register<Gradient>("gui.Gradient", WriteGradients, ReadGradients);

		// Derived, so it belongs with `Resolved` by nature and at the end by
		// rule. Excluded from replication for `Resolved`'s exact reason: every
		// client recomputes it from the tree it was sent, and a bar sized on the
		// authority's canvas is a bar sized for somebody else's window.
		ecs::Components::Register<ScrollState>("gui.ScrollState");

		// Authored, and still at the end because the list is append-only.
		ecs::Components::Register<Selection>("gui.Selection");
		ecs::Components::Register<TableLayout>("gui.TableLayout");
		ecs::Components::Register<PageLayout>("gui.PageLayout");
		ecs::Components::Register<DragDetector>("gui.DragDetector");

		// Derived and local, like `ScrollState` and for a sharper version of
		// its reason: this one holds a moment on *this* process's clock. A
		// client handed a server's timestamp would slide from wherever that
		// server's uptime happened to put it. Excluded from replication in
		// `replication::DefaultReplicatedComponents`; what crosses is
		// `PageLayout::CurrentPage`, and each end animates to it on its own
		// clock.
		ecs::Components::Register<PageMotion>("gui.PageMotion");
		ecs::Components::Register<ScrollMotion>("gui.ScrollMotion");

		// Local presentation policy authored by client scripts. The vector and
		// process-local names deliberately have no file or wire form.
		ecs::Components::Register<SettingsMenuExtensions>("gui.SettingsMenuExtensions", nullptr, nullptr);

		// Appended because component ids are registration order. Each concrete
		// handle leaf owns only the dimensions its geometry consumes.
		ecs::Components::Register<BoxHandleShape>("gui.BoxHandleShape");
		ecs::Components::Register<SphereHandleShape>("gui.SphereHandleShape");
		ecs::Components::Register<CylinderHandleShape>("gui.CylinderHandleShape");
		ecs::Components::Register<LineHandleShape>("gui.LineHandleShape");
		ecs::Components::Register<ConeHandleShape>("gui.ConeHandleShape");
		ecs::Components::Register<HandlesShape>("gui.HandlesShape");
		ecs::Components::Register<ArcHandlesShape>("gui.ArcHandlesShape");
	}
}
