#include <engine/core/Bytes.hpp>
#include <engine/ecs/Components.hpp>
#include <engine/gui/Components.hpp>
#include <engine/gui/Registration.hpp>

#include <array>
#include <cstddef>

namespace engine::gui {

	namespace {
		// Three components hold a `core::Name`, and a name's id is a counter
		// this process assigned in first-seen order. The generated byte
		// serialiser would write that counter, and a reading process would
		// resolve it to whatever string happened to take the same number -
		// which is not a corrupt file, it is a file that loads and is wrong.
		//
		// `scene`'s `WriteVisuals` says the same thing and carries the lesson
		// this repeats deliberately: **a field added to a type with a
		// hand-written serialiser crosses only if somebody remembers, and
		// nothing in the build checks.** So each pair below writes every field
		// of its struct in declaration order, and `gui/tests/Registration.cpp`
		// round-trips a fully-populated value rather than a default one - a
		// default-valued round trip passes whatever you forget.

		void WriteLabels(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *labels = static_cast<const Label *>(source);
			for (size_t index = 0; index < count; index++) {
				const Label &label = labels[index];
				writer.WriteString(label.Text);
				writer.WriteFloat(label.Color.R);
				writer.WriteFloat(label.Color.G);
				writer.WriteFloat(label.Color.B);
				writer.WriteFloat(label.Transparency);
				writer.WriteInt32(label.Size);
				writer.WriteInt8(static_cast<int8_t>(label.Font));
				writer.WriteInt8(static_cast<int8_t>(label.XAlignment));
				writer.WriteInt8(static_cast<int8_t>(label.YAlignment));
				writer.WriteBool(label.Wrapped);
				writer.WriteBool(label.Scaled);
				writer.WriteInt8(static_cast<int8_t>(label.Truncate));
				writer.WriteFloat(label.StrokeColor.R);
				writer.WriteFloat(label.StrokeColor.G);
				writer.WriteFloat(label.StrokeColor.B);
				writer.WriteFloat(label.StrokeTransparency);
				writer.WriteFloat(label.LineHeight);
			}
		}

		void ReadLabels(core::ByteReader &reader, void *destination, size_t count) {
			auto *labels = static_cast<Label *>(destination);
			for (size_t index = 0; index < count; index++) {
				Label &label = labels[index];
				label.Text = std::string(reader.ReadString());
				label.Color.R = reader.ReadFloat();
				label.Color.G = reader.ReadFloat();
				label.Color.B = reader.ReadFloat();
				label.Transparency = reader.ReadFloat();
				label.Size = reader.ReadInt32();
				label.Font = static_cast<FontFace>(reader.ReadInt8());
				label.XAlignment = static_cast<TextXAlignment>(reader.ReadInt8());
				label.YAlignment = static_cast<TextYAlignment>(reader.ReadInt8());
				label.Wrapped = reader.ReadBool();
				label.Scaled = reader.ReadBool();
				label.Truncate = static_cast<TextTruncate>(reader.ReadInt8());
				label.StrokeColor.R = reader.ReadFloat();
				label.StrokeColor.G = reader.ReadFloat();
				label.StrokeColor.B = reader.ReadFloat();
				label.StrokeTransparency = reader.ReadFloat();
				label.LineHeight = reader.ReadFloat();
			}
		}

		void WritePictures(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *pictures = static_cast<const Picture *>(source);
			for (size_t index = 0; index < count; index++) {
				const Picture &picture = pictures[index];
				writer.WriteName(picture.Image);
				writer.WriteFloat(picture.Color.R);
				writer.WriteFloat(picture.Color.G);
				writer.WriteFloat(picture.Color.B);
				writer.WriteFloat(picture.Transparency);
				writer.WriteInt8(static_cast<int8_t>(picture.Scale));
				writer.WriteFloat(picture.SliceCenter.Min.X);
				writer.WriteFloat(picture.SliceCenter.Min.Y);
				writer.WriteFloat(picture.SliceCenter.Max.X);
				writer.WriteFloat(picture.SliceCenter.Max.Y);
				writer.WriteFloat(picture.SliceScale);
				writer.WriteFloat(picture.TileSize.X.Scale);
				writer.WriteFloat(picture.TileSize.X.Offset);
				writer.WriteFloat(picture.TileSize.Y.Scale);
				writer.WriteFloat(picture.TileSize.Y.Offset);
				writer.WriteFloat(picture.RectOffset.X);
				writer.WriteFloat(picture.RectOffset.Y);
				writer.WriteFloat(picture.RectSize.X);
				writer.WriteFloat(picture.RectSize.Y);

				// **Added at v0.18, in the same breath as the field - see
				// `WriteVisuals`' own comment for what happens when that
				// discipline slips.**
				writer.WriteName(picture.Shader);
			}
		}

		void ReadPictures(core::ByteReader &reader, void *destination, size_t count) {
			auto *pictures = static_cast<Picture *>(destination);
			for (size_t index = 0; index < count; index++) {
				Picture &picture = pictures[index];
				picture.Image = reader.ReadName();
				picture.Color.R = reader.ReadFloat();
				picture.Color.G = reader.ReadFloat();
				picture.Color.B = reader.ReadFloat();
				picture.Transparency = reader.ReadFloat();
				picture.Scale = static_cast<ScaleType>(reader.ReadInt8());
				picture.SliceCenter.Min.X = reader.ReadFloat();
				picture.SliceCenter.Min.Y = reader.ReadFloat();
				picture.SliceCenter.Max.X = reader.ReadFloat();
				picture.SliceCenter.Max.Y = reader.ReadFloat();
				picture.SliceScale = reader.ReadFloat();
				picture.TileSize.X.Scale = reader.ReadFloat();
				picture.TileSize.X.Offset = reader.ReadFloat();
				picture.TileSize.Y.Scale = reader.ReadFloat();
				picture.TileSize.Y.Offset = reader.ReadFloat();
				picture.RectOffset.X = reader.ReadFloat();
				picture.RectOffset.Y = reader.ReadFloat();
				picture.RectSize.X = reader.ReadFloat();
				picture.RectSize.Y = reader.ReadFloat();
				picture.Shader = reader.ReadName();
			}
		}

		void WriteEntries(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *entries = static_cast<const Entry *>(source);
			for (size_t index = 0; index < count; index++) {
				const Entry &entry = entries[index];
				writer.WriteString(entry.PlaceholderText);
				writer.WriteFloat(entry.PlaceholderColor.R);
				writer.WriteFloat(entry.PlaceholderColor.G);
				writer.WriteFloat(entry.PlaceholderColor.B);
				writer.WriteBool(entry.ClearTextOnFocus);
				writer.WriteBool(entry.MultiLine);
				writer.WriteBool(entry.TextEditable);

				// **The caret is not written and reads back as unfocused.** It
				// is where somebody's cursor is, which is not a fact about the
				// game - a save file that restored a text box mid-edit would be
				// restoring a session rather than a scene, and a *replica* that
				// received one would move the local player's caret.
				writer.WriteInt32(-1);
				writer.WriteInt32(-1);
			}
		}

		void ReadEntries(core::ByteReader &reader, void *destination, size_t count) {
			auto *entries = static_cast<Entry *>(destination);
			for (size_t index = 0; index < count; index++) {
				Entry &entry = entries[index];
				entry.PlaceholderText = std::string(reader.ReadString());
				entry.PlaceholderColor.R = reader.ReadFloat();
				entry.PlaceholderColor.G = reader.ReadFloat();
				entry.PlaceholderColor.B = reader.ReadFloat();
				entry.ClearTextOnFocus = reader.ReadBool();
				entry.MultiLine = reader.ReadBool();
				entry.TextEditable = reader.ReadBool();
				entry.CursorPosition = reader.ReadInt32();
				entry.SelectionStart = reader.ReadInt32();
			}
		}
	}

	void RegisterGuiComponents() {
		// Order is deliberate and not alphabetical, exactly as `scene`'s list
		// is: it decides component ids, which decide the order archetypes
		// iterate their columns in. **Add at the end.**
		//
		// The authored ones first, then the modifiers, then the one derived
		// component - which puts `Resolved` last, where a reader looking for
		// "what does the layout write" finds it without reading the rest.
		ecs::Components::Register<Element>("gui.Element");
		ecs::Components::Register<Background>("gui.Background");
		ecs::Components::Register<Label>("gui.Label", WriteLabels, ReadLabels);
		ecs::Components::Register<Picture>("gui.Picture", WritePictures, ReadPictures);
		ecs::Components::Register<Button>("gui.Button");
		ecs::Components::Register<Scrolling>("gui.Scrolling");
		ecs::Components::Register<Entry>("gui.Entry", WriteEntries, ReadEntries);
		ecs::Components::Register<Layer>("gui.Layer");
		ecs::Components::Register<Canvas>("gui.Canvas");
		ecs::Components::Register<Surface>("gui.Surface");
		ecs::Components::Register<Billboard>("gui.Billboard");
		ecs::Components::Register<Group>("gui.Group");
		ecs::Components::Register<Viewport>("gui.Viewport");

		ecs::Components::Register<Padding>("gui.Padding");
		ecs::Components::Register<ListLayout>("gui.ListLayout");
		ecs::Components::Register<GridLayout>("gui.GridLayout");
		ecs::Components::Register<AspectRatio>("gui.AspectRatio");
		ecs::Components::Register<SizeLimits>("gui.SizeLimits");
		ecs::Components::Register<TextSizeLimits>("gui.TextSizeLimits");
		ecs::Components::Register<Corner>("gui.Corner");
		ecs::Components::Register<Stroke>("gui.Stroke");
		ecs::Components::Register<Scale>("gui.Scale");

		// **Derived, and it still has a stable registered name.** It is written
		// every frame by the layout pass and nothing replicates it - the
		// authority and the replica derive it identically from the same tree,
		// which is `scene::Visibility`'s argument - but a component with only
		// the automatic name `Components::Of<T>` mints from the compiler's
		// spelling is one two processes cannot agree on, and a snapshot taken
		// in a studio and restored in a test would be one of those two.
		ecs::Components::Register<Resolved>("gui.Resolved");

		// **Derived too, and at the end for the reason the block below repeats.**
		// Written by whoever holds a camera and a world - `render` today - and
		// read by `CanvasFor`. A world that nobody draws never gets one, which is
		// exactly the case the authored fallback is for.
		ecs::Components::Register<SpatialCanvas>("gui.SpatialCanvas");

		// **After `Resolved`, because the rule above is "add at the end".** The
		// order decides component ids, which decide the column order an
		// archetype iterates - so inserting this among the authored ones to keep
		// the grouping tidy would renumber everything after it and change what a
		// recording made before this version means.
		//
		// It carries an `ecs::Entity`, which crosses as an id and a generation
		// and needs no hand-written serialiser: unlike a `core::Name`, an entity
		// id means the same thing in the file it was written from and the world
		// it is read into, because that is what `ecs::Store::Load` remaps.
		ecs::Components::Register<GuiServiceState>("gui.GuiServiceState");

		// The 3D branch, at the end for the reason the rule above gives.
		ecs::Components::Register<Adornment>("gui.Adornment");
		ecs::Components::Register<SelectionOutline>("gui.SelectionOutline");
		ecs::Components::Register<HandleShape>("gui.HandleShape");
	}
}
