#include <engine/core/Bytes.hpp>
#include <engine/ecs/Components.hpp>
#include <engine/gui/Animation.hpp>
#include <engine/gui/Binding.hpp>
#include <engine/gui/Components.hpp>
#include <engine/gui/Modal.hpp>
#include <engine/gui/Registration.hpp>
#include <engine/gui/SettingsMenu.hpp>
#include <engine/gui/Style.hpp>
#include <engine/gui/VirtualCollection.hpp>

#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <stdexcept>
#include <utility>

namespace engine::gui {

	namespace {
		// A viewer-local facet still occupies its ordinary row after restore, but
		// its values must not survive a checkpoint. Keeping the component avoids
		// a module-specific post-load pass while every fresh value is derived by
		// the local layout, input, binding, or presentation pass.
		template <class T> void WriteTransientStates(core::ByteWriter &, const void *, size_t) {}

		template <class T> void ReadTransientStates(core::ByteReader &, void *destination, size_t count) {
			auto *states = static_cast<T *>(destination);
			for (size_t index = 0; index < count; index++) {
				states[index] = {};
			}
		}

		// Three components hold a `core::Name`, and a name's id is a counter
		// this process assigned in first-seen order. The generated byte
		// serialiser would write that counter, and a reading process would
		// resolve it to whatever string happened to take the same number -
		// which is not a corrupt file, it is a file that loads and is wrong.
		//
		// `scene`'s `WriteVisuals` says the same thing and carries the lesson
		// this repeats deliberately: **a field added to a type with a
		// hand-written serialiser crosses only if somebody remembers, and
		// nothing in the build checks.** So each pair below writes every field
		// of its struct in declaration order, and `gui/tests/Registration.cpp`
		// round-trips a fully-populated value rather than a default one - a
		// default-valued round trip passes whatever you forget.

		void WriteLabels(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *labels = static_cast<const Label *>(source);
			for (size_t index = 0; index < count; index++) {
				const Label &label = labels[index];
				writer.WriteString(label.Text);
				writer.WriteFloat(label.Color.R);
				writer.WriteFloat(label.Color.G);
				writer.WriteFloat(label.Color.B);
				writer.WriteFloat(label.Transparency);
				writer.WriteInt32(label.Size);
				writer.WriteInt8(static_cast<int8_t>(label.Font));
				writer.WriteInt8(static_cast<int8_t>(label.XAlignment));
				writer.WriteInt8(static_cast<int8_t>(label.YAlignment));
				writer.WriteBool(label.Wrapped);
				writer.WriteBool(label.Scaled);
				writer.WriteInt8(static_cast<int8_t>(label.Truncate));
				writer.WriteFloat(label.StrokeColor.R);
				writer.WriteFloat(label.StrokeColor.G);
				writer.WriteFloat(label.StrokeColor.B);
				writer.WriteFloat(label.StrokeTransparency);
				writer.WriteFloat(label.LineHeight);

				// **Added at v0.18, in the same breath as the fields.** This
				// pair is exactly the discipline the comment above this function
				// exists to keep, and the reason it is written down twice.
				writer.WriteInt32(label.MaxVisible);
				writer.WriteBool(label.Rich);
			}
		}

		void ReadLabels(core::ByteReader &reader, void *destination, size_t count) {
			auto *labels = static_cast<Label *>(destination);
			for (size_t index = 0; index < count; index++) {
				Label &label = labels[index];
				label.Text = std::string(reader.ReadString());
				label.Color.R = reader.ReadFloat();
				label.Color.G = reader.ReadFloat();
				label.Color.B = reader.ReadFloat();
				label.Transparency = reader.ReadFloat();
				label.Size = reader.ReadInt32();
				label.Font = static_cast<FontFace>(reader.ReadInt8());
				label.XAlignment = static_cast<TextXAlignment>(reader.ReadInt8());
				label.YAlignment = static_cast<TextYAlignment>(reader.ReadInt8());
				label.Wrapped = reader.ReadBool();
				label.Scaled = reader.ReadBool();
				label.Truncate = static_cast<TextTruncate>(reader.ReadInt8());
				label.StrokeColor.R = reader.ReadFloat();
				label.StrokeColor.G = reader.ReadFloat();
				label.StrokeColor.B = reader.ReadFloat();
				label.StrokeTransparency = reader.ReadFloat();
				label.LineHeight = reader.ReadFloat();
				label.MaxVisible = reader.ReadInt32();
				label.Rich = reader.ReadBool();
			}
		}

		void WriteLabelPresentations(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *presentations = static_cast<const LabelPresentation *>(source);
			for (size_t index = 0; index < count; index++) {
				writer.WriteName(presentations[index].LocalizationKey);
			}
		}

		void ReadLabelPresentations(core::ByteReader &reader, void *destination, size_t count) {
			auto *presentations = static_cast<LabelPresentation *>(destination);
			for (size_t index = 0; index < count; index++) {
				presentations[index].LocalizationKey = reader.ReadName();
			}
		}

		bool ValidLocalizedArgumentType(LocalizedArgumentType type) {
			return type == LocalizedArgumentType::String || type == LocalizedArgumentType::Number ||
				   type == LocalizedArgumentType::Date;
		}

		bool ValidLocalizedArgument(const LabelLocalizationArgument &argument) {
			return argument.Name.IsValid() && ValidLocalizedArgumentType(argument.Type) &&
				   argument.String.size() <= LabelLocalizationArguments::MAXIMUM_STRING_BYTES &&
				   (argument.Type != LocalizedArgumentType::Number || std::isfinite(argument.Number));
		}

		void WriteLabelLocalizationArguments(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *arguments = static_cast<const LabelLocalizationArguments *>(source);
			for (size_t row = 0; row < count; row++) {
				const LabelLocalizationArguments &value = arguments[row];
				if (value.Count > LabelLocalizationArguments::MAXIMUM_ARGUMENTS) {
					throw std::length_error("too many localized label arguments");
				}
				writer.WriteUInt8(value.Count);
				for (size_t index = 0; index < value.Count; index++) {
					const LabelLocalizationArgument &argument = value.Values[index];
					if (!ValidLocalizedArgument(argument)) {
						throw std::length_error("invalid localized label argument");
					}
					for (size_t previous = 0; previous < index; previous++) {
						if (value.Values[previous].Name == argument.Name) {
							throw std::length_error("duplicate localized label argument");
						}
					}
					writer.WriteName(argument.Name);
					writer.WriteUInt8(static_cast<uint8_t>(argument.Type));
					switch (argument.Type) {
					case LocalizedArgumentType::String:
						writer.WriteString(argument.String);
						break;
					case LocalizedArgumentType::Number:
						writer.WriteDouble(argument.Number);
						break;
					case LocalizedArgumentType::Date:
						writer.WriteInt64(argument.UnixSeconds);
						break;
					}
				}
			}
		}

		void ReadLabelLocalizationArguments(core::ByteReader &reader, void *destination, size_t count) {
			auto *arguments = static_cast<LabelLocalizationArguments *>(destination);
			for (size_t row = 0; row < count; row++) {
				LabelLocalizationArguments decoded;
				decoded.Count = reader.ReadUInt8();
				if (decoded.Count > LabelLocalizationArguments::MAXIMUM_ARGUMENTS) {
					reader.Fail();
					continue;
				}
				for (size_t index = 0; index < decoded.Count; index++) {
					LabelLocalizationArgument &argument = decoded.Values[index];
					argument.Name = reader.ReadName();
					argument.Type = static_cast<LocalizedArgumentType>(reader.ReadUInt8());
					if (!argument.Name.IsValid() || !ValidLocalizedArgumentType(argument.Type)) {
						reader.Fail();
						break;
					}
					switch (argument.Type) {
					case LocalizedArgumentType::String:
						argument.String = std::string(reader.ReadString());
						if (argument.String.size() > LabelLocalizationArguments::MAXIMUM_STRING_BYTES)
							reader.Fail();
						break;
					case LocalizedArgumentType::Number:
						argument.Number = reader.ReadDouble();
						if (!std::isfinite(argument.Number)) reader.Fail();
						break;
					case LocalizedArgumentType::Date:
						argument.UnixSeconds = reader.ReadInt64();
						break;
					}
					for (size_t previous = 0; previous < index; previous++) {
						if (decoded.Values[previous].Name == argument.Name) reader.Fail();
					}
				}
				if (!reader.Failed()) arguments[row] = std::move(decoded);
			}
		}

		void WriteStyleSet(core::ByteWriter &writer, const StyleSet &set) {
			writer.WriteUInt32(static_cast<uint32_t>(set.Declarations().size()));
			for (const StyleDeclaration &declaration : set.Declarations()) {
				writer.WriteName(declaration.Name);
				writer.WriteUInt8(static_cast<uint8_t>(declaration.Value.Type));
				if (declaration.Value.Type == StyleValueType::Color) {
					writer.WriteFloat(declaration.Value.Color.R);
					writer.WriteFloat(declaration.Value.Color.G);
					writer.WriteFloat(declaration.Value.Color.B);
				} else {
					writer.WriteFloat(declaration.Value.Number);
				}
			}
		}

		bool ReadStyleSet(core::ByteReader &reader, StyleSet &set) {
			set = {};
			const uint32_t count = reader.ReadUInt32();
			if (count > StyleSet::MAXIMUM_DECLARATIONS) {
				reader.Fail();
				return false;
			}
			for (uint32_t index = 0; index < count; index++) {
				StyleDeclaration declaration;
				declaration.Name = reader.ReadName();
				declaration.Value.Type = static_cast<StyleValueType>(reader.ReadUInt8());
				if (declaration.Value.Type == StyleValueType::Color) {
					declaration.Value.Color = {reader.ReadFloat(), reader.ReadFloat(), reader.ReadFloat()};
				} else if (declaration.Value.Type == StyleValueType::Number) {
					declaration.Value.Number = reader.ReadFloat();
				} else {
					reader.Fail();
					return false;
				}
				if (!set.Set(declaration)) {
					reader.Fail();
					return false;
				}
			}
			return true;
		}

		void WriteUIThemes(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *themes = static_cast<const UITheme *>(source);
			for (size_t index = 0; index < count; index++) {
				WriteStyleSet(writer, themes[index].Tokens);
			}
		}

		void ReadUIThemes(core::ByteReader &reader, void *destination, size_t count) {
			auto *themes = static_cast<UITheme *>(destination);
			for (size_t index = 0; index < count; index++) {
				(void)ReadStyleSet(reader, themes[index].Tokens);
			}
		}

		void WriteStyleClasses(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *classes = static_cast<const StyleClass *>(source);
			for (size_t index = 0; index < count; index++) {
				writer.WriteUInt32(static_cast<uint32_t>(classes[index].Names.Names().size()));
				for (const core::Name name : classes[index].Names.Names()) {
					writer.WriteName(name);
				}
			}
		}

		void ReadStyleClasses(core::ByteReader &reader, void *destination, size_t count) {
			auto *classes = static_cast<StyleClass *>(destination);
			for (size_t index = 0; index < count; index++) {
				classes[index] = {};
				const uint32_t names = reader.ReadUInt32();
				if (names > StyleClasses::MAXIMUM_CLASSES) {
					reader.Fail();
					continue;
				}
				for (uint32_t name = 0; name < names; name++) {
					if (!classes[index].Names.Add(reader.ReadName())) {
						reader.Fail();
					}
				}
			}
		}

		void WriteUIStyles(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *styles = static_cast<const UIStyle *>(source);
			for (size_t index = 0; index < count; index++) {
				writer.WriteName(styles[index].Rule.Class);
				writer.WriteUInt8(static_cast<uint8_t>(styles[index].Rule.State));
				WriteStyleSet(writer, styles[index].Rule.Declarations);
			}
		}

		void ReadUIStyles(core::ByteReader &reader, void *destination, size_t count) {
			auto *styles = static_cast<UIStyle *>(destination);
			for (size_t index = 0; index < count; index++) {
				styles[index].Rule.Class = reader.ReadName();
				styles[index].Rule.State = static_cast<StyleState>(reader.ReadUInt8());
				if ((static_cast<uint8_t>(styles[index].Rule.State) & ~static_cast<uint8_t>(0x3f)) != 0) {
					reader.Fail();
				}
				(void)ReadStyleSet(reader, styles[index].Rule.Declarations);
			}
		}

		void WritePresentationValue(core::ByteWriter &writer, const PresentationValue &value) {
			writer.WriteUInt8(static_cast<uint8_t>(value.Type));
			switch (value.Type) {
			case PresentationValueType::Color:
				writer.WriteFloat(value.Color.R);
				writer.WriteFloat(value.Color.G);
				writer.WriteFloat(value.Color.B);
				return;
			case PresentationValueType::Number:
				writer.WriteFloat(value.Number);
				return;
			case PresentationValueType::UDim2:
				writer.WriteFloat(value.UDim2.X.Scale);
				writer.WriteFloat(value.UDim2.X.Offset);
				writer.WriteFloat(value.UDim2.Y.Scale);
				writer.WriteFloat(value.UDim2.Y.Offset);
				return;
			}
		}

		PresentationValue ReadPresentationValue(core::ByteReader &reader) {
			PresentationValue value;
			value.Type = static_cast<PresentationValueType>(reader.ReadUInt8());
			switch (value.Type) {
			case PresentationValueType::Color:
				value.Color = core::Color3{reader.ReadFloat(), reader.ReadFloat(), reader.ReadFloat()};
				break;
			case PresentationValueType::Number:
				value.Number = reader.ReadFloat();
				break;
			case PresentationValueType::UDim2:
				value.UDim2 = core::UDim2{
					reader.ReadFloat(), reader.ReadFloat(), reader.ReadFloat(), reader.ReadFloat()
				};
				break;
			default:
				reader.Fail();
				break;
			}
			return value;
		}

		void WriteAnimationPlaybacks(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *playbacks = static_cast<const AnimationPlayback *>(source);
			for (size_t index = 0; index < count; index++) {
				const AnimationPlayback &playback = playbacks[index];
				const core::TweenInfo &tween = playback.Clip.Tween;
				writer.WriteBool(playback.Playing);
				writer.WriteFloat(tween.Time);
				writer.WriteFloat(tween.DelayTime);
				writer.WriteInt32(tween.RepeatCount);
				writer.WriteUInt8(static_cast<uint8_t>(tween.Style));
				writer.WriteUInt8(static_cast<uint8_t>(tween.Direction));
				writer.WriteBool(tween.Reverses);
				writer.WriteUInt32(static_cast<uint32_t>(playback.Clip.Tracks().size()));
				for (const PresentationTrack &track : playback.Clip.Tracks()) {
					writer.WriteUInt8(static_cast<uint8_t>(track.Property));
					writer.WriteUInt32(static_cast<uint32_t>(track.Keys().size()));
					for (const PresentationKey &key : track.Keys()) {
						writer.WriteFloat(key.Time);
						WritePresentationValue(writer, key.Value);
					}
				}
				writer.WriteUInt32(static_cast<uint32_t>(playback.Clip.Markers().size()));
				for (const AnimationMarker &marker : playback.Clip.Markers()) {
					writer.WriteName(marker.Name);
					writer.WriteFloat(marker.Time);
				}
			}
		}

		void ReadAnimationPlaybacks(core::ByteReader &reader, void *destination, size_t count) {
			auto *playbacks = static_cast<AnimationPlayback *>(destination);
			for (size_t index = 0; index < count; index++) {
				AnimationPlayback playback;
				playback.StartedAt = -1.0;
				playback.Playing = reader.ReadBool();
				core::TweenInfo &tween = playback.Clip.Tween;
				tween.Time = reader.ReadFloat();
				tween.DelayTime = reader.ReadFloat();
				tween.RepeatCount = reader.ReadInt32();
				tween.Style = static_cast<core::EasingStyle>(reader.ReadUInt8());
				tween.Direction = static_cast<core::EasingDirection>(reader.ReadUInt8());
				tween.Reverses = reader.ReadBool();

				const uint32_t tracks = reader.ReadUInt32();
				if (tracks > UIAnimation::MAXIMUM_TRACKS) {
					reader.Fail();
				}
				for (uint32_t trackIndex = 0; trackIndex < tracks && !reader.Failed(); trackIndex++) {
					PresentationTrack track;
					track.Property = static_cast<PresentationProperty>(reader.ReadUInt8());
					const uint32_t keys = reader.ReadUInt32();
					if (keys > PresentationTrack::MAXIMUM_KEYS) {
						reader.Fail();
						break;
					}
					for (uint32_t keyIndex = 0; keyIndex < keys && !reader.Failed(); keyIndex++) {
						if (!track.Add(PresentationKey{reader.ReadFloat(), ReadPresentationValue(reader)})) {
							reader.Fail();
						}
					}
					if (!reader.Failed() && !playback.Clip.AddTrack(track)) {
						reader.Fail();
					}
				}

				const uint32_t markers = reader.ReadUInt32();
				if (markers > UIAnimation::MAXIMUM_MARKERS) {
					reader.Fail();
				}
				for (uint32_t markerIndex = 0; markerIndex < markers && !reader.Failed(); markerIndex++) {
					const std::string_view name = reader.ReadString();
					if (name.size() > UIAnimation::MAXIMUM_MARKER_NAME_BYTES ||
						!playback.Clip.AddMarker(AnimationMarker{core::Name(name), reader.ReadFloat()})) {
						reader.Fail();
					}
				}

				PresentationOverrides sampled;
				if (!reader.Failed() && !SamplePresentation(playback.Clip, 0.0, sampled)) {
					reader.Fail();
				}
				playbacks[index] = reader.Failed() ? AnimationPlayback{} : playback;
			}
		}

		// **`gui.Gradient` is here for a different reason from the three above,
		// and it is a size rather than a correctness one.**
		//
		// A `core::ColorSequence` is twenty keypoint slots and a count, and a
		// `core::NumberSequence` is twenty more - 656 of the component's 672
		// bytes. The generated writer copies the object representation, so every
		// gradient in every world wrote all forty slots into every save and
		// every replication delta, whatever `Count` said. **A default two-stop
		// gradient is thirty-two meaningful bytes of ramp**, and it was costing
		// 656.
		//
		// So this writes `Count` and then that many stops, exactly as
		// `effects`'s ribbon pair does for the same two types. `Sequence::Add`
		// on the way back in is what keeps a hostile file from claiming a count
		// past the capacity.
		void WriteRamp(core::ByteWriter &writer, const core::ColorSequence &sequence) {
			writer.WriteUInt32(sequence.Count);
			for (uint32_t stop = 0; stop < sequence.Count; stop++) {
				writer.WriteFloat(sequence.Keypoints[stop].Time);
				writer.WriteFloat(sequence.Keypoints[stop].Value.R);
				writer.WriteFloat(sequence.Keypoints[stop].Value.G);
				writer.WriteFloat(sequence.Keypoints[stop].Value.B);
			}
		}

		void ReadRamp(core::ByteReader &reader, core::ColorSequence &sequence) {
			sequence = core::ColorSequence{};
			const uint32_t stops = reader.ReadUInt32();
			for (uint32_t stop = 0; stop < stops && !reader.Failed(); stop++) {
				const float at = reader.ReadFloat();
				const float red = reader.ReadFloat();
				const float green = reader.ReadFloat();
				const float blue = reader.ReadFloat();
				(void)sequence.Add(core::ColorKeypoint{at, core::Color3{red, green, blue}});
			}
		}

		void WriteCurve(core::ByteWriter &writer, const core::NumberSequence &sequence) {
			writer.WriteUInt32(sequence.Count);
			for (uint32_t stop = 0; stop < sequence.Count; stop++) {
				writer.WriteFloat(sequence.Keypoints[stop].Time);
				writer.WriteFloat(sequence.Keypoints[stop].Value);
				writer.WriteFloat(sequence.Keypoints[stop].Envelope);
			}
		}

		void ReadCurve(core::ByteReader &reader, core::NumberSequence &sequence) {
			sequence = core::NumberSequence{};
			const uint32_t stops = reader.ReadUInt32();
			for (uint32_t stop = 0; stop < stops && !reader.Failed(); stop++) {
				const float at = reader.ReadFloat();
				const float value = reader.ReadFloat();
				const float envelope = reader.ReadFloat();
				(void)sequence.Add(core::NumberKeypoint{at, value, envelope});
			}
		}

		void WriteGradients(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *gradients = static_cast<const Gradient *>(source);
			for (size_t index = 0; index < count; index++) {
				const Gradient &gradient = gradients[index];
				WriteRamp(writer, gradient.Color);
				WriteCurve(writer, gradient.Transparency);
				writer.WriteFloat(gradient.Offset.X);
				writer.WriteFloat(gradient.Offset.Y);
				writer.WriteFloat(gradient.Rotation);
				writer.WriteBool(gradient.Enabled);
			}
		}

		void ReadGradients(core::ByteReader &reader, void *destination, size_t count) {
			auto *gradients = static_cast<Gradient *>(destination);
			for (size_t index = 0; index < count; index++) {
				Gradient &gradient = gradients[index];
				ReadRamp(reader, gradient.Color);
				ReadCurve(reader, gradient.Transparency);
				gradient.Offset.X = reader.ReadFloat();
				gradient.Offset.Y = reader.ReadFloat();
				gradient.Rotation = reader.ReadFloat();
				gradient.Enabled = reader.ReadBool();
			}
		}

		void WritePictures(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *pictures = static_cast<const Picture *>(source);
			for (size_t index = 0; index < count; index++) {
				const Picture &picture = pictures[index];
				writer.WriteName(picture.Image);
				writer.WriteFloat(picture.Color.R);
				writer.WriteFloat(picture.Color.G);
				writer.WriteFloat(picture.Color.B);
				writer.WriteFloat(picture.Transparency);
				writer.WriteInt8(static_cast<int8_t>(picture.Scale));
				writer.WriteFloat(picture.SliceCenter.Min.X);
				writer.WriteFloat(picture.SliceCenter.Min.Y);
				writer.WriteFloat(picture.SliceCenter.Max.X);
				writer.WriteFloat(picture.SliceCenter.Max.Y);
				writer.WriteFloat(picture.SliceScale);
				writer.WriteFloat(picture.TileSize.X.Scale);
				writer.WriteFloat(picture.TileSize.X.Offset);
				writer.WriteFloat(picture.TileSize.Y.Scale);
				writer.WriteFloat(picture.TileSize.Y.Offset);
				writer.WriteFloat(picture.RectOffset.X);
				writer.WriteFloat(picture.RectOffset.Y);
				writer.WriteFloat(picture.RectSize.X);
				writer.WriteFloat(picture.RectSize.Y);

				// **Added at v0.18, in the same breath as the field - see
				// `WriteVisuals`' own comment for what happens when that
				// discipline slips.**
				writer.WriteName(picture.Shader);

				// **Added at v0.18, in the same breath as the fields**, which is
				// the discipline the comment above exists to keep.
				writer.WriteName(picture.HoverImage);
				writer.WriteName(picture.PressedImage);
				writer.WriteInt8(static_cast<int8_t>(picture.Resample));
			}
		}

		void ReadPictures(core::ByteReader &reader, void *destination, size_t count) {
			auto *pictures = static_cast<Picture *>(destination);
			for (size_t index = 0; index < count; index++) {
				Picture &picture = pictures[index];
				picture.Image = reader.ReadName();
				picture.Color.R = reader.ReadFloat();
				picture.Color.G = reader.ReadFloat();
				picture.Color.B = reader.ReadFloat();
				picture.Transparency = reader.ReadFloat();
				picture.Scale = static_cast<ScaleType>(reader.ReadInt8());
				picture.SliceCenter.Min.X = reader.ReadFloat();
				picture.SliceCenter.Min.Y = reader.ReadFloat();
				picture.SliceCenter.Max.X = reader.ReadFloat();
				picture.SliceCenter.Max.Y = reader.ReadFloat();
				picture.SliceScale = reader.ReadFloat();
				picture.TileSize.X.Scale = reader.ReadFloat();
				picture.TileSize.X.Offset = reader.ReadFloat();
				picture.TileSize.Y.Scale = reader.ReadFloat();
				picture.TileSize.Y.Offset = reader.ReadFloat();
				picture.RectOffset.X = reader.ReadFloat();
				picture.RectOffset.Y = reader.ReadFloat();
				picture.RectSize.X = reader.ReadFloat();
				picture.RectSize.Y = reader.ReadFloat();
				picture.Shader = reader.ReadName();
				picture.HoverImage = reader.ReadName();
				picture.PressedImage = reader.ReadName();
				picture.Resample = static_cast<ResampleMode>(reader.ReadInt8());
			}
		}

		void WriteEntries(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *entries = static_cast<const Entry *>(source);
			for (size_t index = 0; index < count; index++) {
				const Entry &entry = entries[index];
				writer.WriteString(entry.PlaceholderText);
				writer.WriteFloat(entry.PlaceholderColor.R);
				writer.WriteFloat(entry.PlaceholderColor.G);
				writer.WriteFloat(entry.PlaceholderColor.B);
				writer.WriteBool(entry.ClearTextOnFocus);
				writer.WriteBool(entry.MultiLine);
				writer.WriteBool(entry.TextEditable);
				writer.WriteBool(entry.Password);

				// **The caret is not written and reads back as unfocused.** It
				// is where somebody's cursor is, which is not a fact about the
				// game - a save file that restored a text box mid-edit would be
				// restoring a session rather than a scene, and a *replica* that
				// received one would move the local player's caret.
				writer.WriteInt32(-1);
				writer.WriteInt32(-1);
			}
		}

		void ReadEntries(core::ByteReader &reader, void *destination, size_t count) {
			auto *entries = static_cast<Entry *>(destination);
			for (size_t index = 0; index < count; index++) {
				Entry &entry = entries[index];
				entry.PlaceholderText = std::string(reader.ReadString());
				entry.PlaceholderColor.R = reader.ReadFloat();
				entry.PlaceholderColor.G = reader.ReadFloat();
				entry.PlaceholderColor.B = reader.ReadFloat();
				entry.ClearTextOnFocus = reader.ReadBool();
				entry.MultiLine = reader.ReadBool();
				entry.TextEditable = reader.ReadBool();
				entry.Password = reader.ReadBool();
				entry.CursorPosition = reader.ReadInt32();
				entry.SelectionStart = reader.ReadInt32();
			}
		}

		void WriteNodeCanvasNodes(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *nodes = static_cast<const NodeCanvasNode *>(source);
			for (size_t index = 0; index < count; index++) {
				const NodeCanvasNode &node = nodes[index];
				writer.WriteName(node.Id);
				writer.WriteName(node.Type);
				writer.WriteString(node.Title);
				writer.WriteBool(node.Enabled);
				writer.WriteInt8(static_cast<int8_t>(node.BypassMode));
				writer.WriteName(node.BypassInput);
				writer.WriteName(node.BypassOutput);
				writer.WriteFloat(node.MinimumSize.X);
				writer.WriteFloat(node.MinimumSize.Y);
				writer.WriteBool(node.Resizable);
				writer.WriteInt8(static_cast<int8_t>(node.InputLayout));
			}
		}

		void ReadNodeCanvasNodes(core::ByteReader &reader, void *destination, size_t count) {
			auto *nodes = static_cast<NodeCanvasNode *>(destination);
			for (size_t index = 0; index < count; index++) {
				NodeCanvasNode &node = nodes[index];
				node.Id = reader.ReadName();
				node.Type = reader.ReadName();
				node.Title = std::string(reader.ReadString());
				node.Enabled = reader.ReadBool();
				node.BypassMode = static_cast<NodeBypassMode>(reader.ReadInt8());
				node.BypassInput = reader.ReadName();
				node.BypassOutput = reader.ReadName();
				node.MinimumSize.X = reader.ReadFloat();
				node.MinimumSize.Y = reader.ReadFloat();
				node.Resizable = reader.ReadBool();
				node.InputLayout = static_cast<InputPortLayout>(reader.ReadInt8());
			}
		}

		void WriteNodeCanvasGroups(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *groups = static_cast<const NodeCanvasGroup *>(source);
			for (size_t index = 0; index < count; index++) {
				const NodeCanvasGroup &group = groups[index];
				writer.WriteName(group.Id);
				writer.WriteString(group.Title);
				writer.WriteFloat(group.Padding.X);
				writer.WriteFloat(group.Padding.Y);
				writer.WriteInt8(static_cast<int8_t>(group.Layout));
			}
		}

		void ReadNodeCanvasGroups(core::ByteReader &reader, void *destination, size_t count) {
			auto *groups = static_cast<NodeCanvasGroup *>(destination);
			for (size_t index = 0; index < count; index++) {
				NodeCanvasGroup &group = groups[index];
				group.Id = reader.ReadName();
				group.Title = std::string(reader.ReadString());
				group.Padding.X = reader.ReadFloat();
				group.Padding.Y = reader.ReadFloat();
				group.Layout = static_cast<NodeGroupLayout>(reader.ReadInt8());
			}
		}

		void WriteNodeCanvasPorts(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *ports = static_cast<const NodeCanvasPort *>(source);
			for (size_t index = 0; index < count; index++) {
				const NodeCanvasPort &port = ports[index];
				writer.WriteName(port.Id);
				writer.WriteName(port.ValueType);
				writer.WriteInt8(static_cast<int8_t>(port.Direction));
				writer.WriteInt8(static_cast<int8_t>(port.Edge));
				writer.WriteInt32(port.MaxConnections);
			}
		}

		void ReadNodeCanvasPorts(core::ByteReader &reader, void *destination, size_t count) {
			auto *ports = static_cast<NodeCanvasPort *>(destination);
			for (size_t index = 0; index < count; index++) {
				NodeCanvasPort &port = ports[index];
				port.Id = reader.ReadName();
				port.ValueType = reader.ReadName();
				port.Direction = static_cast<NodePortDirection>(reader.ReadInt8());
				port.Edge = static_cast<NodePortEdge>(reader.ReadInt8());
				port.MaxConnections = reader.ReadInt32();
			}
		}

		void WriteNodeCanvasLinks(core::ByteWriter &writer, const void *source, size_t count) {
			const auto *links = static_cast<const NodeCanvasLink *>(source);
			for (size_t index = 0; index < count; index++) {
				const NodeCanvasLink &link = links[index];
				writer.WriteName(link.FromNode);
				writer.WriteName(link.FromPort);
				writer.WriteInt8(static_cast<int8_t>(link.FromDirection));
				writer.WriteName(link.ToNode);
				writer.WriteName(link.ToPort);
				writer.WriteInt8(static_cast<int8_t>(link.ToDirection));
				writer.WriteFloat(link.LineColor.R);
				writer.WriteFloat(link.LineColor.G);
				writer.WriteFloat(link.LineColor.B);
				writer.WriteFloat(link.LineTransparency);
				writer.WriteFloat(link.LineThickness);
			}
		}

		void ReadNodeCanvasLinks(core::ByteReader &reader, void *destination, size_t count) {
			auto *links = static_cast<NodeCanvasLink *>(destination);
			for (size_t index = 0; index < count; index++) {
				NodeCanvasLink &link = links[index];
				link.FromNode = reader.ReadName();
				link.FromPort = reader.ReadName();
				link.FromDirection = static_cast<NodePortDirection>(reader.ReadInt8());
				link.ToNode = reader.ReadName();
				link.ToPort = reader.ReadName();
				link.ToDirection = static_cast<NodePortDirection>(reader.ReadInt8());
				link.LineColor.R = reader.ReadFloat();
				link.LineColor.G = reader.ReadFloat();
				link.LineColor.B = reader.ReadFloat();
				link.LineTransparency = reader.ReadFloat();
				link.LineThickness = reader.ReadFloat();
			}
		}
	}

	void RegisterGuiComponents() {
		// Order is deliberate and not alphabetical, exactly as `scene`'s list
		// is: it decides component ids, which decide the order archetypes
		// iterate their columns in. **Add at the end.**
		//
		// The authored ones first, then the modifiers, then the one derived
		// component - which puts `Resolved` last, where a reader looking for
		// "what does the layout write" finds it without reading the rest.
		ecs::Components::Register<Element>("gui.Element");
		ecs::Components::Register<Background>("gui.Background");
		ecs::Components::Register<Label>("gui.Label", WriteLabels, ReadLabels);
		ecs::Components::Register<LabelPresentation>(
			"gui.LabelPresentation", WriteLabelPresentations, ReadLabelPresentations
		);
		ecs::Components::Register<Picture>("gui.Picture", WritePictures, ReadPictures);
		ecs::Components::Register<Button>("gui.Button");
		ecs::Components::Register<Scrolling>("gui.Scrolling");
		ecs::Components::Register<Entry>("gui.Entry", WriteEntries, ReadEntries);
		ecs::Components::Register<Layer>("gui.Layer");
		ecs::Components::Register<Canvas>(
			"gui.Canvas", WriteTransientStates<Canvas>, ReadTransientStates<Canvas>
		);
		ecs::Components::Register<CanvasTransform>(
			"gui.CanvasTransform", WriteTransientStates<CanvasTransform>, ReadTransientStates<CanvasTransform>
		);
		ecs::Components::Register<Surface>("gui.Surface");
		ecs::Components::Register<Billboard>("gui.Billboard");
		ecs::Components::Register<Group>("gui.Group");
		ecs::Components::Register<Viewport>("gui.Viewport");

		ecs::Components::Register<Padding>("gui.Padding");
		ecs::Components::Register<ListLayout>("gui.ListLayout");
		ecs::Components::Register<GridLayout>("gui.GridLayout");
		ecs::Components::Register<AspectRatio>("gui.AspectRatio");
		ecs::Components::Register<SizeLimits>("gui.SizeLimits");
		ecs::Components::Register<TextSizeLimits>("gui.TextSizeLimits");
		ecs::Components::Register<Corner>("gui.Corner");
		ecs::Components::Register<Stroke>("gui.Stroke");
		ecs::Components::Register<Scale>("gui.Scale");

		// **Derived, and it still has a stable registered name.** It is written
		// every frame by the layout pass and nothing replicates it - the
		// authority and the replica derive it identically from the same tree,
		// which is `scene::Visibility`'s argument - but a component with only
		// the automatic name `Components::Of<T>` mints from the compiler's
		// spelling is one two processes cannot agree on, and a snapshot taken
		// in a studio and restored in a test would be one of those two.
		ecs::Components::Register<Resolved>(
			"gui.Resolved", WriteTransientStates<Resolved>, ReadTransientStates<Resolved>
		);

		// **Derived too, and at the end for the reason the block below repeats.**
		// Written by whoever holds a camera and a world - `render` today - and
		// read by `CanvasFor`. A world that nobody draws never gets one, which is
		// exactly the case the authored fallback is for.
		ecs::Components::Register<SpatialCanvas>(
			"gui.SpatialCanvas", WriteTransientStates<SpatialCanvas>, ReadTransientStates<SpatialCanvas>
		);

		// **After `Resolved`, because the rule above is "add at the end".** The
		// order decides component ids, which decide the column order an
		// archetype iterates - so inserting this among the authored ones to keep
		// the grouping tidy would renumber everything after it and change what a
		// recording made before this version means.
		//
		// It carries an `ecs::Entity`, which crosses as an id and a generation
		// and needs no hand-written serialiser: unlike a `core::Name`, an entity
		// id means the same thing in the file it was written from and the world
		// it is read into, because that is what `ecs::Store::Load` remaps.
		ecs::Components::Register<GuiServiceState>(
			"gui.GuiServiceState", WriteTransientStates<GuiServiceState>, ReadTransientStates<GuiServiceState>
		);
		ecs::Components::Register<TextCompositionState>(
			"gui.TextCompositionState",
			WriteTransientStates<TextCompositionState>,
			ReadTransientStates<TextCompositionState>
		);

		// The 3D branch, at the end for the reason the rule above gives.
		ecs::Components::Register<Adornment>("gui.Adornment");
		ecs::Components::Register<AdornmentInteraction>("gui.AdornmentInteraction");
		ecs::Components::Register<SelectionOutline>("gui.SelectionOutline");
		ecs::Components::Register<HandleShape>("gui.HandleShape");

		// A modifier by nature, and still registered after the 3D branch:
		// the list is append-only because ids decide archetype column order,
		// so arriving at v0.17 puts it here rather than beside `Scale`.
		ecs::Components::Register<FlexItem>("gui.FlexItem");

		// Append-only, for the reason above. Trivially copyable despite holding
		// two sequences - `core::Sequence` is fixed-capacity precisely so that a
		// ramp can be a component, and its own header carries the argument.
		ecs::Components::Register<Gradient>("gui.Gradient", WriteGradients, ReadGradients);

		// Derived, so it belongs with `Resolved` by nature and at the end by
		// rule. Excluded from replication for `Resolved`'s exact reason: every
		// client recomputes it from the tree it was sent, and a bar sized on the
		// authority's canvas is a bar sized for somebody else's window.
		ecs::Components::Register<ScrollState>(
			"gui.ScrollState", WriteTransientStates<ScrollState>, ReadTransientStates<ScrollState>
		);

		// Authored, and still at the end because the list is append-only.
		ecs::Components::Register<Selection>("gui.Selection");
		ecs::Components::Register<TableLayout>("gui.TableLayout");
		ecs::Components::Register<PageLayout>("gui.PageLayout");
		ecs::Components::Register<DragDetector>("gui.DragDetector");

		// Derived and local, like `ScrollState` and for a sharper version of
		// its reason: this one holds a moment on *this* process's clock. A
		// client handed a server's timestamp would slide from wherever that
		// server's uptime happened to put it. Excluded from replication in
		// `replication::DefaultReplicatedComponents`; what crosses is
		// `PageLayout::CurrentPage`, and each end animates to it on its own
		// clock.
		ecs::Components::Register<PageMotion>(
			"gui.PageMotion", WriteTransientStates<PageMotion>, ReadTransientStates<PageMotion>
		);
		ecs::Components::Register<ScrollMotion>(
			"gui.ScrollMotion", WriteTransientStates<ScrollMotion>, ReadTransientStates<ScrollMotion>
		);

		// Local presentation policy authored by client scripts. The vector and
		// process-local names deliberately have no file or wire form.
		ecs::Components::Register<SettingsMenuExtensions>(
			"gui.SettingsMenuExtensions",
			WriteTransientStates<SettingsMenuExtensions>,
			ReadTransientStates<SettingsMenuExtensions>
		);

		// Appended because component ids are registration order. Each concrete
		// handle leaf owns only the dimensions its geometry consumes.
		ecs::Components::Register<BoxHandleShape>("gui.BoxHandleShape");
		ecs::Components::Register<SphereHandleShape>("gui.SphereHandleShape");
		ecs::Components::Register<CylinderHandleShape>("gui.CylinderHandleShape");
		ecs::Components::Register<LineHandleShape>("gui.LineHandleShape");
		ecs::Components::Register<ConeHandleShape>("gui.ConeHandleShape");
		ecs::Components::Register<HandlesShape>("gui.HandlesShape");
		ecs::Components::Register<ArcHandlesShape>("gui.ArcHandlesShape");

		// Appended because component ids decide archetype column order. This
		// separate row preserves LabelPresentation's older wire layout.
		ecs::Components::Register<LabelLocalizationArguments>(
			"gui.LabelLocalizationArguments", WriteLabelLocalizationArguments, ReadLabelLocalizationArguments
		);

		// The graph model is authored and crosses a save or replica. Its names
		// must be written as text rather than process-local ids, so the explicit
		// serializers live beside the other name-bearing GUI components.
		ecs::Components::Register<NodeCanvas>("gui.NodeCanvas");
		ecs::Components::Register<NodeCanvasNode>(
			"gui.NodeCanvasNode", WriteNodeCanvasNodes, ReadNodeCanvasNodes
		);
		ecs::Components::Register<NodeCanvasGroup>(
			"gui.NodeCanvasGroup", WriteNodeCanvasGroups, ReadNodeCanvasGroups
		);
		ecs::Components::Register<NodeCanvasPort>(
			"gui.NodeCanvasPort", WriteNodeCanvasPorts, ReadNodeCanvasPorts
		);
		ecs::Components::Register<NodeCanvasLink>(
			"gui.NodeCanvasLink", WriteNodeCanvasLinks, ReadNodeCanvasLinks
		);

		RegisterBindingComponents();
		RegisterVirtualCollectionComponents();
		RegisterModalComponents();

		// The authored clip writes its bounded tracks explicitly because a raw
		// representation would persist private capacity and process-local marker
		// names. The sampled state is rebuilt per view from explicit time.
		ecs::Components::Register<AnimationPlayback>(
			"gui.AnimationPlayback",
			WriteAnimationPlaybacks,
			ReadAnimationPlaybacks,
			static_cast<uint32_t>(
				1 + 4 + 4 + 4 + 1 + 1 + 1 + 4 +
				UIAnimation::MAXIMUM_TRACKS *
					(1 + 4 + PresentationTrack::MAXIMUM_KEYS * (4 + 1 + 4 * sizeof(float))) +
				4 + UIAnimation::MAXIMUM_MARKERS * (4 + UIAnimation::MAXIMUM_MARKER_NAME_BYTES + 4)
			)
		);
		ecs::Components::Register<PresentationState>(
			"gui.PresentationState",
			WriteTransientStates<PresentationState>,
			ReadTransientStates<PresentationState>
		);

		// The authored theme vocabulary uses custom byte forms because Names and
		// StyleSet's fixed capacities must survive a save independently of this
		// process's intern table. ResolvedStyle is local compile output.
		ecs::Components::Register<UITheme>("gui.UITheme", WriteUIThemes, ReadUIThemes);
		ecs::Components::Register<StyleClass>("gui.StyleClass", WriteStyleClasses, ReadStyleClasses);
		ecs::Components::Register<StyleDirect>("gui.StyleDirect");
		ecs::Components::Register<UIStyle>("gui.UIStyle", WriteUIStyles, ReadUIStyles);
		ecs::Components::Register<ThemeBinding>("gui.ThemeBinding");
		ecs::Components::Register<ResolvedStyle>(
			"gui.ResolvedStyle", WriteTransientStates<ResolvedStyle>, ReadTransientStates<ResolvedStyle>
		);

		// Appended because component identifiers are durable. A mask is authored
		// and serialisable, while its resolved operation is compile output.
		ecs::Components::Register<Mask>("gui.Mask");
	}
}
