#include <engine/imagegraph/SourceCommonDispatch.hpp>

#include <algorithm>
#include <array>

namespace engine::imagegraph {
	namespace {
		struct DispatchRow {
			std::string_view SourceType;
			SourceCommonDispatch Dispatch;
		};
		// Audited from pinned source b69eca232217360cf1502ef0223523d818606652 constructor inheritance.
		// Rows include every mapped catalogue source class plus the structural Collection base.
		constexpr std::array<DispatchRow, 887> Dispatches{{
			{"Node_2D_Extrude", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_2D_light", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Affector", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Camera", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Camera_Set", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Displace", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Get_Data", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Instancer", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Light_Directional",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Light_Point", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Material", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Cone", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Cube", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Cylinder", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Export", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Extrude", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Extrude_Mesh",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Json", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Obj", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Path_Extrude",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Path_Revolve",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Plane", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Sphere_Ico",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Sphere_UV", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Stack_Slice",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Terrain", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Torus", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Vertex_Points",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mesh_Wall_Builder",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Mirror", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Particle", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Point_Affector", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Repeat", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Round_Vertex", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Scene", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Set_Material", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Set_Origin", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Subdivide", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Transform", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Transform_Image",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_Transform_Scene",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_3D_UV_Remap", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_9Slice", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_ASE_File_Read", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_ASE_Tag", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_ASE_Tileset", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_ASE_layer", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Active_Canvas", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Align_Content", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Alpha_Cutoff", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Alpha_Grey", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Ambient_Occlusion", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Anim_Curve", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Anim_Loop", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Animation_Control", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Application_In", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Application_Out", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Area", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Argument", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Armature", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Armature_Bind", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Armature_Bone", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Armature_From_Path",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Armature_IK", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Armature_Mesh_Rig", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Armature_Mirror", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Armature_Path", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Armature_Pose", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Armature_Pose_Bone",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Armature_Pose_Stagger",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Armature_Sample", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Armature_Skin", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Armature_Subdivide",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Add", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Boolean_Opr", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_CSV_Parse", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Composite", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Convolute", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Copy", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Cumulative", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Find", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Flattern", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Get", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Insert", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Length", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Partition", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Pin", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Randomizer", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Range", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Rearrange", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Remove", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Reverse", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Sample", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Set", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Shift", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Shuffle", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Sort", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Split", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Transpose", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Trim", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Uniform", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Unique", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Array_Zip", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Assert", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Atlas", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Atlas_Affector", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Atlas_Draw", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Atlas_Get", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Atlas_Set", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Atlas_Struct", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Audio_Loudness", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Audio_Window", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Average", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_BW", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Background", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Barrel_Distort", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Base_Convert", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Bend", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Bevel", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Bit_Reduce", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Blend", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Blend_Depth", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Blend_Edge", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Blend_Height", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Blobify", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Bloom", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Blur", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Blur_Bokeh", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Blur_Box", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Blur_Contrast", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Blur_Directional", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Blur_Path", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Blur_Radial", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Blur_Shape", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Blur_Simple", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Blur_Slope", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Blur_Zoom", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Boolean", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Box_Pattern", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Brush_Linear", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Buffer_to_String", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Byte_File_Read", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Byte_File_Write", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_CSV_File_Read", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_CSV_File_Write", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Cache", {SourceCommonStepKind::CacheOverride, SourceCommonWrapperKind::Lite}},
			{"Node_Cache_Array", {SourceCommonStepKind::CacheOverride, SourceCommonWrapperKind::Full}},
			{"Node_Cache_Results", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Lite}},
			{"Node_Cache_Value_Array", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Camera", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Canvas", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Canvas_S", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Caustic", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Cellular", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Cellular_Cube", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Checker", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Chromatic_Aberration",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Collection", {SourceCommonStepKind::CollectionOverride, SourceCommonWrapperKind::Lite}},
			{"Node_Color", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Color_Blind", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Color_Data", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Color_HSV", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Color_Math", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Color_Mix", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Color_OKLCH", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Color_RGB", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Color_Remove", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Color_Select", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Color_Separate", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Color_adjust", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Color_replace", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Color_to_HSV", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Color_to_OKLCH", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Color_to_RGB", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Colorize", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Colors_Replace", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Combine_HSV", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Combine_RGB", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Compare", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Compose_Texture", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Composite", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Composite_Tag", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Condition", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Lite}},
			{"Node_Convolution", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Corner", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Corner_Data", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Counter", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Crack_Pattern", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Crop", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Crop_Content", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Cross_Section", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Curvature", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Curve", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Curve_Function", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Curve_HSV", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Datetime_Get", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_De_Corner", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_De_Stray", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Deblur", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Delay", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Delay_Value", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Differential", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Diffuse", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Dilate", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Directory_Search", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Displace", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Display_Image", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Display_Text",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Unsupported}},
			{"Node_Dither", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Dither_Diffuse", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Dotted", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Downscale", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Edge_Detect", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Emboss", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Equation", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Erode", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Export", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Extends", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_FFT", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_FLIP_Apply_Force", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_FLIP_Apply_Velocity",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_FLIP_Destroy", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_FLIP_Domain", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_FLIP_Fill", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_FLIP_Group_Inline", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_FLIP_Render", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_FLIP_Repel", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_FLIP_Solid", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_FLIP_Spawner", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_FLIP_Update", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_FLIP_Vortex", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_FLIP_to_VFX", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_FXAA", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Feedback", {SourceCommonStepKind::CollectionOverride, SourceCommonWrapperKind::Lite}},
			{"Node_Feedback_Input", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Lite}},
			{"Node_Feedback_Output", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Find_Pixel", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Flip", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Flood_Fill", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Flow_Noise", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Flow_Path", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Fluffify", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Fn_Ease", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Fn_Math", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Fn_SmoothStep", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Fn_WaveTable", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Fold_Noise", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Font_Bitmap", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Font_Data", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Frame", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Unsupported}},
			{"Node_Fur", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_GMRoom", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Gabor_Noise", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Gamma_Map", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Gap_Contract", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Globalvar", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Glow", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Gradient", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Gradient_Cos", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Gradient_Cube", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Gradient_Extract", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Gradient_Grid", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Gradient_Out", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Gradient_Palette", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Gradient_Path", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Gradient_Points", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Gradient_Points_N", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Gradient_Replace_Color",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Gradient_Sample", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Gradient_Shift", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Grain", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Graph_Preview", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Grey_Alpha", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Greyscale", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Grid", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Grid_Hex", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Grid_Pentagonal", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Grid_Tri", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Grid_Warp", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Group", {SourceCommonStepKind::CollectionOverride, SourceCommonWrapperKind::Lite}},
			{"Node_Group_Input", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Lite}},
			{"Node_Group_Output", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Group_Thumbnail", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_HLSL", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_HSV_Channel", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_HTTP_Request_File", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_HTTP_request", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Heightmap_Project_3D",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Herringbone_Tile", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_High_Pass", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Hilbert", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Honeycomb_Noise", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Hough_Transform", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Image", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Image_Animated", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Image_Grid", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Image_Grid_Patreon",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Image_List_Bug", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Image_Sequence", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Image_Sheet", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Image_gif", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Image_mp4", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Interlaced", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Interpret_Matrix", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Interpret_Number", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Invert", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_IsoSurf", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Iterate", {SourceCommonStepKind::CollectionOverride, SourceCommonWrapperKind::Lite}},
			{"Node_Iterate_Each_File_Inline",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Iterate_Each_Inline",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Iterate_Filter_Inline",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Iterate_Sort_Inline",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Iterator_Each_Length",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Iterator_Input", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Lite}},
			{"Node_Iterator_Length", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Iterator_Output", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Iterator_Reduce_Inline",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_JPEG", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Json_File_Read", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Json_File_Write", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Julia_Set", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Kisrhombille", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Krita_File_Read", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Krita_layer", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Kuwahara", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_LUT", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Layer_Output", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Level", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Level_Selector", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Line", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Line_2Points", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Line_Match", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Linearize", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Liquefy", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Local_Analyze", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Logic", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Lua_Compute", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Lua_Global", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Lua_Surface", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MIDI_In", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Blast_Align", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Blast_Attract", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Blast_Combine", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Blast_Flame", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Blast_Force", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Blast_Gravity", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Blast_Inline", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Blast_Particle", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Blast_Render", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Blast_Smoke", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Blast_Wave", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Blinker", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Brownian", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Cable", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Circuit", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Cloud", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Delay_Machine", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Dialog", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Drip", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Facet", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Fall", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Flag", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Flake", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Flare", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Fracture", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_GodRay", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Grass", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_GridBalls", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_GridFlip", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_IsoCube", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Isoextrude", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Jigsaw", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Panels", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Parallax", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Pile", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Rain", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Rock", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Saber", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Smoke", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Sparkle", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Subpixel", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tile", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Add_Branch",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Add_Leaf", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Attract", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Branch", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Branch_Fan",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Branch_Reroot",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Branch_To_Path",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Branch_Trim",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Bush", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Ground_Branch",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Grow", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Inline", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Leaf", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Leaf_Hull", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Leaf_Particle",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Leaf_to_Points",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Path_Root", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Render", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Repulse", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Root", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Smoothen_Branch",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Spiral_Branch",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Subdivide_Branch",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Wave_Branch",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Wiggle", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_Tree_Wiggle_Leaf",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_MK_WireFrame", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Markov", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Markov_Gradient", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Math", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Lite}},
			{"Node_Matrix", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_Color_Apply",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_Crop", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_Det", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_Eigen", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_Get", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_Get_Vector", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_Identity", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_Invert", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_Math", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_Multiply_Vector",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_Projection", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_Set", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_Set_Vector", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_To_Array", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_Transform_2D",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_Transform_3D",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Matrix_Transpose", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Maze_Pattern", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Mesh_Create_Lattice",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Mesh_Create_Path", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Mesh_Transform", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Mesh_Warp", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Mirror", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Mirror_Path", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Mirror_Polar", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Monitor_Capture", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Morph_Surface", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Move_Point", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Multiply_Alpha", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Noise", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Noise_Aniso", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Noise_Blue", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Noise_Bubble", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Noise_Cristal", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Noise_Gaussian", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Noise_Scratch", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Noise_Simplex", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Noise_Strand", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Normal", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Normal_Adjust", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Normal_Blend", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Normal_Light", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Normal_to_Height", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Normalize", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Number", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Lite}},
			{"Node_Number_Simple", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Lite}},
			{"Node_Number_Text_Format",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_ORA_File_Read", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_ORA_layer", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Offset", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Outline", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Override_Channel", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Box", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Box_BBOX", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Box_Mirror", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Box_Point", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Box_Split", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Crop_PBBOX", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Dimension", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Draw_Curve", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Draw_Diamond", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Draw_Ellipse", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Draw_Line", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Draw_Pie", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Draw_Polygon", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Draw_Quadrilateral",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Draw_Rectangle", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Draw_Round_Rectangle",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Draw_Star", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Draw_Surface", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Draw_Trapezoid", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Draw_Triangle", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_FX_Bevel", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_FX_Extrude", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_FX_Highlight", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_FX_Shine", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Filter_Mirror", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Filter_Polar", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PB_Output", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PCX_Array_Get", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PCX_Array_Set", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PCX_Condition", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PCX_Equation", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PCX_fn_Math", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PCX_fn_Random", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PCX_fn_Surface_Height",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PCX_fn_Surface_Width",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PCX_fn_var", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PCX_var", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_PXC", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Pack_Sprites", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Padding", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Padding_Data", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Palette", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Palette_Extract", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Palette_Replace", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Palette_Shift", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Palette_Shrink", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Palette_Sort", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Particle", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_3D", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_3D_Camera", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_3D_Transform", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Anchor", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Array", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Bake", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Blend", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Bridge", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Builder", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Extends", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Fill", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Flattern", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_From_Mask", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Join", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_L_System", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Length", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Map", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Map_Area", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Morph", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Offset", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Plot", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Profile", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Redistribute", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Remap", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Repeat", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Reverse", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Revolve", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_SDF", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Sample", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Scatter", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Separate_Folder",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Shape", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Shape_3D", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Shift", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Skew", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Smooth", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Smoothen", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Spiral", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Transform", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Trim", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Wave", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_Weight_Adjust",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Path_to_Curve", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Perlin", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Perlin_Cube", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Perlin_Extra", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Pin", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Lite}},
			{"Node_Pixel_Builder", {SourceCommonStepKind::CollectionOverride, SourceCommonWrapperKind::Lite}},
			{"Node_Pixel_Cloud", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Pixel_Extract", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Pixel_Math", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Pixel_Sampler", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Pixel_Sort", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Plot_Linear", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Point_3D_Camera", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Point_In_Area", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Point_SDF", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Points_Remap", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Points_Triangulate",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Polar", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Posterize", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Print", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Project_Data", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Project_Layer", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Project_Output", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Pytagorean_Tile", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Quarternion_From_Euler",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Quarternion_Lookat",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Quarternion_To_Euler",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Quasicrystal", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_RD", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_RGB_Channel", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_RM_Cloud", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_RM_Combine", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_RM_Primitive", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_RM_Render", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_RM_Render_Cross", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_RM_Render_Scatter", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_RM_Terrain", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_RM_to_Mesh", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_RM_to_Voxel", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Random", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Random_Shape", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Random_Tile", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rate_Remap", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Recursive_Subdiv", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Refract", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Region_Fill", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Render_Sprite_Sheet",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Repeat", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Repeat_Texture", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Revert", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Ribbon", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Ridge_Noise", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Activate", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Explode", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Force_Apply", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Fracture", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Group_Inline",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Joint_Fix", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Joint_Rotate",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Object", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Object_Get_Collision",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Object_Segment",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Object_Spawner",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Override", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Path_Collider",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Render", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Render_ID", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Sensor", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Variable", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rigid_Wall", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rotation_Random_Data",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Rotation_Range_Data",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_SDF", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_SVG", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Sampler", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Scale", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Scale_Algo", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Scale_Content_Aware",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Scatter", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Scatter_Point_Fibonacci",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Scatter_Point_Lattice",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Scatter_Point_Lattice_3D",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Scatter_Points", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Scatter_Points_3D", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Scatter_Sampler", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Sec_Convert", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Segment_Filter", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Separate", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Seperate_Shape", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Sequence_Anim", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Shadow", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Shadow_Cast", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Shape", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Shape_3D", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Shape_Ellipse", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Shape_Fast", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Lite}},
			{"Node_Shape_Half", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Shape_Map", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Shape_Polygon", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Shape_Rectangle", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Shard_Noise", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Shell", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Shuffle", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Simple_Pattern", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Simplex_Cube", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Skew", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Sky", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Slideshow", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Slideshow_Node_Anchor",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Smear", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Smoke_Add", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Smoke_Add_Collider",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Smoke_Apply_Velocity",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Smoke_Domain", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Smoke_Domain_Queue",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Smoke_Group_Inline",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Smoke_Render", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Smoke_Repulse", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Smoke_Turbulence", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Smoke_Update", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Smoke_Vortex", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Solid", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Spherize", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Spout_Receive", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Spout_Send", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Sprite_Stack", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Stack", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Stagger", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Statistic", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Straighten", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Strand_Break", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Strand_Collision", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Strand_Create", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Strand_Force_Apply",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Strand_Gravity", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Strand_Group_Inline",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Strand_Length_Adjust",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Strand_Render", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Strand_Render_Texture",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Strand_Update", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Stretch", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_String", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_String_Change_Case",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_String_Count", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_String_Delete", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_String_Format", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_String_Get_Char", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_String_Insert", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_String_Join", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_String_Length", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_String_Merge", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_String_Regex_Match",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_String_Regex_Replace",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_String_Regex_Search",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_String_Replace", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_String_Split", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_String_Trim", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Stripe", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Struct", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Struct_Get", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Struct_JSON_Parse", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Struct_Set", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Surface_Cube", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Surface_From_Buffer",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Surface_Is_Empty", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Surface_Project_3D",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Surface_Project_Cylinder_3D",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Surface_Project_Volume_3D",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Surface_Replace", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Surface_Tag", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Surface_To_Buffer", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Surface_To_Points", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Surface_data", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Switch", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Symmetric_NN", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Terminal_Trigger", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Text", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Text_File_Read", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Text_File_Write", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Texture_Remap", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Threshold", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Threshold_Switch", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Tile", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Tile_Convert", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Tile_Drawer", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Tile_Random", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Tile_Render", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Tile_Rule", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Tile_Tilemap_Export",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Tile_Tileset", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Time_Remap", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_To_Number", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_To_Text", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Tonemap_ACE", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Track_Pixel", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Trail", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Transform", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Transform_Array", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Trigger", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Trigger_Bool", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Tunnel_In", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Tunnel_Out", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_UI_Delay", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_UV_Area", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_UV_Blend", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_UV_Cartesian", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_UV_Height", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_UV_Isometric", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_UV_Perspective", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_UV_Polar", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Unicode", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VFX_Accelerate", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VFX_Attract", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VFX_Boids", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VFX_Destroy", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VFX_Group_Inline", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VFX_Oscillate", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VFX_Override", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VFX_Renderer", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VFX_Repel", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VFX_Spawner", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VFX_Trail", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VFX_Triangulate", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VFX_Turbulence", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VFX_Variable", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VFX_Vortex", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VFX_Wind", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Vector2", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Vector3", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Vector4", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Vector_Cart_To_Polar",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Vector_Cross_2D", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Vector_Cross_3D", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Vector_Direction", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Vector_Dot", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Vector_Magnitude", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Vector_Math", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Lite}},
			{"Node_Vector_Normalize", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Vector_Polar_To_Cart",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Vector_Split", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Vector_Swizzle", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Bloat", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Collide", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Drag", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Force", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Inline", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Mesh", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Mesh_Bridge",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Mesh_Cache",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Mesh_Cache_Lerp",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Mesh_Disk",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Mesh_Grid",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Mesh_Pin",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Mesh_Pleat",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Mesh_Tear",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Path", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Render", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Step", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_Wind", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_VerletSim_to_Path", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Vignette", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Voronoi_Extra", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_WAV_File_Read", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_WAV_File_Write", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Warp", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Wave_Interfere", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Wavelet_Noise", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Weave", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Websocket_Receiver",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Websocket_Sender", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Weld", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Widget_Test", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Wiggler", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Wrap_Area", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_XDoG_Threshold", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_XML_File_Read", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_XML_File_Write", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_Zigzag", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Acceleration",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Align_to_Velocity",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Attract",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Blend", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Boids", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Clone", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Collision",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Destroy",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Follow_Path",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Gravity",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Inline", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Mask", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Mask_Data",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Render_Model",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Snap_Transform",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Spawn", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Trail", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Transform",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_Wiggle", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_3D_from_Points",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Acceleration",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Align_to_Velocity",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Attract", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Blend", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Boids", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Clone", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Collision", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Destroy", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Follow_Path",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Gravity", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Inline", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Mask", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Mask_Data", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Mask_Distance",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Oscillate", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Render", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Render_Line",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Render_Path",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Render_Point",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Render_Trail",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Render_Triangle",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Sample_Color",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Snap_Transform",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Spawn", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Transform", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Triangulate",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Trigger_Event",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Vector_Field",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Vector_Gradient",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Wiggle", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_Wrap", {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
			{"Node_pSystem_from_Points",
			 {SourceCommonStepKind::NodeDataCommon, SourceCommonWrapperKind::Full}},
		}};
		static_assert([] {
			for (size_t index = 1; index < Dispatches.size(); ++index)
				if (Dispatches[index - 1].SourceType >= Dispatches[index].SourceType) return false;
			return true;
		}());
	}
	SourceCommonDispatch
	SourceCommonDispatchProfile(std::string_view sourceType, bool nativeExecutable) noexcept {
		if (!nativeExecutable && sourceType != "Node_Collection") return {};
		const auto found = std::lower_bound(
			Dispatches.begin(),
			Dispatches.end(),
			sourceType,
			[](const DispatchRow &row, std::string_view name) { return row.SourceType < name; }
		);
		return found != Dispatches.end() && found->SourceType == sourceType ? found->Dispatch
																			: SourceCommonDispatch{};
	}
}
