#!/usr/bin/env python3
"""Focused checks for the standalone Ninja and ccache build profiler."""

from __future__ import annotations

from importlib.util import module_from_spec, spec_from_file_location
from io import StringIO
from pathlib import Path
import contextlib
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[2]
SPEC = spec_from_file_location("build_profile", ROOT / "scripts" / "build-profile.py")
if SPEC is None or SPEC.loader is None:
	raise RuntimeError("could not load scripts/build-profile.py")
MODULE = module_from_spec(SPEC)
sys.modules[SPEC.name] = MODULE
SPEC.loader.exec_module(MODULE)


class BuildProfileTest(unittest.TestCase):
	def test_ninja_profile_expands_unity_sources_and_groups_work(self) -> None:
		with tempfile.TemporaryDirectory() as temporary:
			build = Path(temporary)
			unity = build / "mono.client/CMakeFiles/client_lib.dir/Unity/unity_0_cxx.cxx"
			unity.parent.mkdir(parents=True)
			unity.write_text(
				"/* generated by CMake */\n#include \"/repo/mono.client/src/Client.cpp\"\n"
				"#include \"/repo/mono.client/src/Scene.cpp\"\n",
				encoding="utf-8",
			)
			(build / ".ninja_log").write_text(
				"# ninja log v5\n"
				"10\t80\t0\tmono.client/CMakeFiles/client_lib.dir/Unity/unity_0_cxx.cxx.o\thash\n"
				"20\t45\t0\tmono.vendor/sqlitecpp/sqlite3/CMakeFiles/sqlite3.dir/sqlite3.c.o\tsqlite-hash\n"
				+ "".join(
					f"100\t150\t0\tmono.tools/generated/output-{index}.txt\tmulti-output-hash\n"
					for index in range(268)
				),
				encoding="utf-8",
			)

			edges = MODULE.read_ninja_log(build / ".ninja_log")
			self.assertEqual(len(edges), 3)
			multi_output = next(edge for edge in edges if edge.command_hash == "multi-output-hash")
			self.assertEqual(multi_output.output_count, 268)
			self.assertEqual(sum(edge.elapsed_milliseconds for edge in edges), 145)

			output = StringIO()
			with contextlib.redirect_stdout(output):
				MODULE.print_edges(build, edges, 3)
			text = output.getvalue()
			self.assertIn("0.140 s", text)
			self.assertIn("retained-log span", text)
			self.assertIn("retains output history across invocations", text)
			self.assertIn("unity unit: Client.cpp, Scene.cpp", text)
			self.assertIn("[268 outputs]", text)
			self.assertIn("mono.client", text)
			self.assertIn("mono.vendor/sqlitecpp", text)
			self.assertIn("not a dependency critical path", text)

	def test_ccache_stats_accumulate_terminal_outcomes_per_unity_unit(self) -> None:
		with tempfile.TemporaryDirectory() as temporary:
			build = Path(temporary)
			unity = build / "mono.engine/core/CMakeFiles/engine_core.dir/Unity/unity_0_cxx.cxx"
			unity.parent.mkdir(parents=True)
			unity.write_text(
				"/* generated by CMake */\n#include \"/repo/mono.engine/core/src/Log.cpp\"\n",
				encoding="utf-8",
			)
			stats = build / "ccache-stats.log"
			stats.write_text(
				"# mono.engine/core/CMakeFiles/engine_core.dir/Unity/unity_0_cxx.cxx\n"
				"direct_cache_hit\nlocal_storage_hit\n"
				"# mono.engine/core/CMakeFiles/engine_core.dir/Unity/unity_0_cxx.cxx\n"
				"cache_miss\nlocal_storage_miss\n"
				"# mono.vendor/miniz/miniz.c\npreprocessed_cache_hit\n"
				"# mono.vendor/unlucky/unlucky.c\ncache_miss\n"
				"# mono.vendor/unlucky/unlucky.c\ncache_miss\n"
				"# mono.vendor/doomed/doomed.c\ncache_miss\n"
				"# mono.vendor/doomed/doomed.c\ncache_miss\n"
				"# mono.vendor/doomed/doomed.c\ncache_miss\n"
				"# mono.tools/uncacheable/flags.cpp\nunsupported_compiler_option\n"
				"# mono.tools/uncacheable/flags.cpp\nunsupported_compiler_option\n"
				"# mono.tools/uncacheable/broken.cpp\ncompiler_error\n",
				encoding="utf-8",
			)

			outcomes = MODULE.read_ccache_stats(stats)
			unity_outcome = outcomes["mono.engine/core/CMakeFiles/engine_core.dir/Unity/unity_0_cxx.cxx"]
			self.assertEqual((unity_outcome.hits, unity_outcome.misses), (1, 1))
			self.assertEqual(outcomes["mono.vendor/miniz/miniz.c"].hits, 1)
			self.assertEqual(outcomes["mono.vendor/unlucky/unlucky.c"].misses, 2)
			self.assertEqual(outcomes["mono.vendor/doomed/doomed.c"].misses, 3)
			flags = outcomes["mono.tools/uncacheable/flags.cpp"]
			self.assertEqual((flags.hits, flags.misses, flags.uncacheable), (0, 0, 2))
			self.assertEqual(flags.reasons, {"unsupported_compiler_option": 2})
			self.assertEqual(outcomes["mono.tools/uncacheable/broken.cpp"].reasons, {"compiler_error": 1})

			output = StringIO()
			with contextlib.redirect_stdout(output):
				MODULE.print_cache(build, stats, 3)
			text = output.getvalue()
			self.assertIn("2 hits, 6 misses, 3 uncacheable across 11 compiler calls, 25.0%", text)
			self.assertIn("unity unit: Log.cpp", text)
			self.assertIn("attribution only", text)
			self.assertIn("translation units that always miss (at least 2 calls)", text)
			self.assertIn("mono.vendor/unlucky/unlucky.c", text)
			self.assertIn("mono.vendor/doomed/doomed.c", text)
			self.assertLess(text.index("mono.vendor/doomed/doomed.c"), text.index("mono.vendor/unlucky/unlucky.c"))
			self.assertIn("translation units repeatedly uncacheable", text)
			self.assertIn("mono.tools/uncacheable/flags.cpp", text)
			self.assertIn("unsupported_compiler_option (2)", text)
			self.assertIn("compiler_error", text)

			hits_only = build / "hits-only.log"
			hits_only.write_text(
				"# mono.vendor/clean/clean.cpp\n"
				"direct_cache_hit\n",
				encoding="utf-8",
			)
			hits_output = StringIO()
			with contextlib.redirect_stdout(hits_output):
				MODULE.print_cache(build, hits_only, 3)
			self.assertIn("top 3 translation units by cumulative misses\n  none", hits_output.getvalue())


if __name__ == "__main__":
	unittest.main()
