#include "Instances.hpp"

#include <engine/ecs/Classes.hpp>
#include <engine/ecs/Components.hpp>

#include <string>
#include <vector>

namespace engine::ecs {

	namespace {
		// How deep a tree this file will walk before deciding it is looking at
		// a cycle rather than at a scene.
		//
		// `SetParent` refuses to make a cycle, so nothing should ever reach
		// this. It exists because the walks that would hang are the ones that
		// build a string or a list as they go, and a hang with a growing
		// allocation behind it is the worst way to find out.
		constexpr size_t MAXIMUM_DEPTH = 4096;

		// One node's tree links, or null when the entity is not an instance.
		const Hierarchy *NodeOf(const StoreState &state, Entity instance) {
			return static_cast<const Hierarchy *>(GetComponent(state, instance, Components::Of<Hierarchy>()));
		}

		// The same, for writing. Every call may move the row it returns a
		// pointer into, so a caller holding two of these at once is holding one
		// that has already gone stale.
		Hierarchy *MutableNodeOf(StoreState &state, Entity instance) {
			return static_cast<Hierarchy *>(
				GetComponentMutable(state, instance, Components::Of<Hierarchy>())
			);
		}

		// Rebuilds a parent's child links after a freed row was left named by
		// them, and answers with the tail that survived.
		//
		// **Reached only once a link is already known bad**, so an intact list
		// pays nothing for this. The walk stops at the first dead child rather
		// than stepping over it because the links *out of* a freed row are gone
		// with the row: there is no way to reach what followed it, and guessing
		// would invent an order the author never wrote.
		Entity RepairChildren(StoreState &state, Entity parent) {
			const Hierarchy *host = NodeOf(state, parent);
			if (host == nullptr) {
				return NULL_ENTITY;
			}

			Entity tail = NULL_ENTITY;
			for (Entity child = host->FirstChild; child != NULL_ENTITY;) {
				const Hierarchy *link = NodeOf(state, child);
				if (link == nullptr) {
					break;
				}
				tail = child;
				child = link->NextSibling;
			}

			// Whatever the walk ended on is the end of the list now, and its
			// `NextSibling` is still naming the row that was freed.
			if (tail != NULL_ENTITY) {
				MutableNodeOf(state, tail)->NextSibling = NULL_ENTITY;
			}

			Hierarchy *node = MutableNodeOf(state, parent);
			if (tail == NULL_ENTITY) {
				node->FirstChild = NULL_ENTITY;
			}
			node->LastChild = tail;
			return tail;
		}

		// Copies one instance without its subtree.
		Entity CloneOne(StoreState &state, Entity source) {
			const EntityId key = EntityId::Of(source);
			const EntityLocation from = *state.Directory.Locate(key.Index);
			if (from.Archetype == EntityLocation::NO_ARCHETYPE) {
				return NULL_ENTITY;
			}

			const ComponentSet &set = state.Tables[from.Archetype].Set();

			const Entity copy = CreateEntity(state);
			if (copy == NULL_ENTITY) {
				// The range is full. Reported by whoever asked; there is no
				// half-made instance to unwind because nothing has been written
				// yet.
				return NULL_ENTITY;
			}

			const EntityId copyKey = EntityId::Of(copy);
			const uint32_t table = TableFor(state, set);
			Relocate(state, copyKey.Index, EntityLocation{}, table);

			// The source row may have moved when the copy was placed, so it is
			// re-read rather than remembered.
			const EntityLocation now = *state.Directory.Locate(key.Index);
			const EntityLocation into = *state.Directory.Locate(copyKey.Index);

			Archetype &destination = state.Tables[into.Archetype];
			Archetype &origin = state.Tables[now.Archetype];

			for (const ComponentId component : set.Ids()) {
				destination.Find(component)->Assign(into.Row, origin.Find(component)->At(now.Row));
			}

			// A copy belongs to no tree until somebody parents it.
			Hierarchy detached;
			destination.Find(Components::Of<Hierarchy>())->Assign(into.Row, &detached);

			return copy;
		}
	}

	void RegisterInstanceComponents() {
		// `InstanceClass` and `Hierarchy` are handles and nothing else, so the
		// generated byte serialisation is the right one: a `ClassId` is a
		// registration index and an `Entity` is a directory index, and a
		// snapshot restores the directory exactly so that handles inside a
		// component stay valid.
		Components::Register<InstanceClass>("ecs.InstanceClass");
		Components::Register<Hierarchy>("ecs.Hierarchy");

		// **`InstanceName` is the one that cannot use it.** It holds a
		// `core::Name`, whose id is first-seen order *within one process* — so
		// the generated serialiser was writing an interning counter into save
		// files, and a world reloaded by a process that had interned its
		// strings in a different order came back with every instance named
		// something else. `Components.hpp` says in as many words that this is
		// the form to use for anything holding a `Name`; this type is the one
		// that most obviously does and was the one that did not.
		Components::Register<InstanceName>(
			"ecs.InstanceName",
			[](core::ByteWriter &writer, const void *values, size_t count) {
				const auto *labels = static_cast<const InstanceName *>(values);
				for (size_t index = 0; index < count; index++) {
					writer.WriteName(labels[index].Value);
				}
			},
			[](core::ByteReader &reader, void *values, size_t count) {
				auto *labels = static_cast<InstanceName *>(values);
				for (size_t index = 0; index < count; index++) {
					labels[index].Value = reader.ReadName();
				}
			}
		);
	}

	Entity CreateInstance(StoreState &state, ClassId id, std::string_view name) {
		const ClassInfo &info = Classes::Describe(id);
		if (info.Set == nullptr) {
			return NULL_ENTITY;
		}

		const Entity entity = CreateEntity(state);
		if (entity == NULL_ENTITY) {
			return NULL_ENTITY;
		}

		const EntityId key = EntityId::Of(entity);

		// Straight into the class's archetype rather than one component at a
		// time. Adding them one by one would walk the entity through every
		// intermediate table on the way, creating each of them.
		const uint32_t table = TableFor(state, *info.Set);
		Relocate(state, key.Index, EntityLocation{}, table);

		const EntityLocation location = *state.Directory.Locate(key.Index);
		Archetype &archetype = state.Tables[location.Archetype];

		// The prototype row, copied column by column. This is what makes a
		// default a value rather than a constructor, and it is the same
		// operation Clone performs from a different source.
		for (const ComponentId component : info.Set->Ids()) {
			if (const void *value = Classes::DefaultOf(id, component); value != nullptr) {
				archetype.Find(component)->Assign(location.Row, value);
			}
		}

		const InstanceClass declared{id};
		archetype.Find(Components::Of<InstanceClass>())->Assign(location.Row, &declared);

		if (!name.empty()) {
			const InstanceName label{core::Name(name)};
			archetype.Find(Components::Of<InstanceName>())->Assign(location.Row, &label);
		}

		return entity;
	}

	ClassId ClassOf(const StoreState &state, Entity instance) {
		const auto *declared = static_cast<const InstanceClass *>(
			GetComponent(state, instance, Components::Of<InstanceClass>())
		);
		return declared == nullptr ? ClassId{} : declared->Class;
	}

	bool IsA(const StoreState &state, Entity instance, ClassId id) {
		return Classes::IsA(ClassOf(state, instance), id);
	}

	core::Name InstanceNameOf(const StoreState &state, Entity instance) {
		const auto *label =
			static_cast<const InstanceName *>(GetComponent(state, instance, Components::Of<InstanceName>()));
		return label == nullptr ? core::Name{} : label->Value;
	}

	Entity ParentOf(const StoreState &state, Entity instance) {
		const Hierarchy *node = NodeOf(state, instance);
		return node == nullptr ? NULL_ENTITY : node->Parent;
	}

	bool HasChildren(const StoreState &state, Entity instance) {
		const Hierarchy *node = NodeOf(state, instance);
		return node != nullptr && node->FirstChild != NULL_ENTITY;
	}

	void EachChild(const StoreState &state, Entity instance, const std::function<void(Entity)> &body) {
		const Hierarchy *node = NodeOf(state, instance);
		if (node == nullptr) {
			return;
		}

		Entity child = node->FirstChild;
		while (child != NULL_ENTITY) {
			// Read before the body runs, so a body that reparents or destroys
			// the child it was handed does not lose its place in the list.
			const Hierarchy *link = NodeOf(state, child);

			// **A link that resolves to nothing ends the walk without being
			// handed over.** It used to call the body first and stop
			// afterwards, so the one thing a caller could not survive — a
			// handle that is not a child, and may not be an entity — was the
			// one thing it was given. `GetChildren()` published it straight to
			// a script, and `RepairChildren` two functions up already breaks
			// before using the same value.
			if (link == nullptr) {
				return;
			}

			const Entity next = link->NextSibling;

			body(child);
			child = next;
		}
	}

	void EachDescendant(const StoreState &state, Entity instance, const std::function<void(Entity)> &body) {
		// **An explicit stack, because a scene's depth is the author's.** The
		// walk this replaced lived in `script` and recursed; a file with ten
		// thousand nested folders in it would have been a stack overflow on
		// open, from data, with nothing to point at.
		//
		// Children are pushed in reverse so they pop in insertion order, which
		// is what makes this the order a hand-written recursive walk produces.
		std::vector<Entity> stack;
		std::vector<Entity> children;

		const auto descend = [&](Entity parent) {
			children.clear();
			EachChild(state, parent, [&children](Entity child) { children.push_back(child); });
			for (size_t index = children.size(); index > 0; index--) {
				stack.push_back(children[index - 1]);
			}
		};

		descend(instance);

		while (!stack.empty()) {
			const Entity at = stack.back();
			stack.pop_back();

			body(at);
			descend(at);
		}
	}

	bool SetInstanceName(StoreState &state, Entity instance, std::string_view name) {
		if (GetComponent(state, instance, Components::Of<InstanceName>()) == nullptr) {
			return false;
		}

		const InstanceName label{name.empty() ? core::Name{} : core::Name(name)};
		SetComponent(state, instance, Components::Of<InstanceName>(), &label);
		return true;
	}

	Entity FindFirstChild(const StoreState &state, Entity instance, std::string_view name, bool recursive) {
		// **An empty query finds nothing, and it used to find the unnamed.**
		// `CreateInstance("")` leaves an instance with no `core::Name` at all,
		// `InstanceNameOf` answers with an invalid one, and an invalid name is
		// what `Name("")` compares equal to — so `FindFirstChild(x, "")` was
		// asking for "whatever has no name" and answering with the first one.
		//
		// Self-consistent, and not what anybody calling it means. Roblox
		// returns nil, and a caller passing a name it read from somewhere and
		// got an empty string for wants nil rather than an arbitrary child.
		if (name.empty()) {
			return NULL_ENTITY;
		}

		const core::Name wanted(name);

		const Hierarchy *node = NodeOf(state, instance);
		if (node == nullptr) {
			return NULL_ENTITY;
		}

		for (Entity child = node->FirstChild; child != NULL_ENTITY;) {
			if (InstanceNameOf(state, child) == wanted) {
				return child;
			}
			const Hierarchy *link = NodeOf(state, child);
			child = link == nullptr ? NULL_ENTITY : link->NextSibling;
		}

		if (!recursive) {
			return NULL_ENTITY;
		}

		// **The children first, then the descendants**, rather than one
		// depth-first pass over both. Roblox's recursive form is documented as
		// finding the nearest match, and a script asking for a name it expects
		// one level down should not get one six levels down inside the first
		// child instead. The loop above has already answered the common case,
		// so the cost of the second pass is only paid by a search that failed.
		Entity found = NULL_ENTITY;
		EachDescendant(state, instance, [&](Entity descendant) {
			if (found == NULL_ENTITY && InstanceNameOf(state, descendant) == wanted) {
				found = descendant;
			}
		});
		return found;
	}

	Entity FindFirstChildOfClass(const StoreState &state, Entity instance, ClassId id) {
		if (!id.IsValid()) {
			return NULL_ENTITY;
		}

		const Hierarchy *node = NodeOf(state, instance);
		if (node == nullptr) {
			return NULL_ENTITY;
		}

		for (Entity child = node->FirstChild; child != NULL_ENTITY;) {
			// Exactly this class. `IsA` would make asking for a `BasePart` find
			// a `Part`, which is what `FindFirstChildWhichIsA` is for.
			if (ClassOf(state, child) == id) {
				return child;
			}
			const Hierarchy *link = NodeOf(state, child);
			child = link == nullptr ? NULL_ENTITY : link->NextSibling;
		}
		return NULL_ENTITY;
	}

	Entity FindFirstChildWhichIsA(const StoreState &state, Entity instance, ClassId id, bool recursive) {
		if (!id.IsValid()) {
			return NULL_ENTITY;
		}

		const Hierarchy *node = NodeOf(state, instance);
		if (node == nullptr) {
			return NULL_ENTITY;
		}

		for (Entity child = node->FirstChild; child != NULL_ENTITY;) {
			if (IsA(state, child, id)) {
				return child;
			}
			const Hierarchy *link = NodeOf(state, child);
			child = link == nullptr ? NULL_ENTITY : link->NextSibling;
		}

		if (!recursive) {
			return NULL_ENTITY;
		}

		Entity found = NULL_ENTITY;
		EachDescendant(state, instance, [&](Entity descendant) {
			if (found == NULL_ENTITY && IsA(state, descendant, id)) {
				found = descendant;
			}
		});
		return found;
	}

	Entity FindFirstAncestor(const StoreState &state, Entity instance, std::string_view name) {
		if (name.empty()) {
			return NULL_ENTITY;
		}

		const core::Name wanted(name);
		for (Entity walk = ParentOf(state, instance); walk != NULL_ENTITY; walk = ParentOf(state, walk)) {
			if (InstanceNameOf(state, walk) == wanted) {
				return walk;
			}
		}
		return NULL_ENTITY;
	}

	Entity FindFirstAncestorOfClass(const StoreState &state, Entity instance, ClassId id) {
		if (!id.IsValid()) {
			return NULL_ENTITY;
		}

		for (Entity walk = ParentOf(state, instance); walk != NULL_ENTITY; walk = ParentOf(state, walk)) {
			if (ClassOf(state, walk) == id) {
				return walk;
			}
		}
		return NULL_ENTITY;
	}

	Entity FindFirstAncestorWhichIsA(const StoreState &state, Entity instance, ClassId id) {
		if (!id.IsValid()) {
			return NULL_ENTITY;
		}

		for (Entity walk = ParentOf(state, instance); walk != NULL_ENTITY; walk = ParentOf(state, walk)) {
			if (IsA(state, walk, id)) {
				return walk;
			}
		}
		return NULL_ENTITY;
	}

	std::string GetFullName(const StoreState &state, Entity instance) {
		if (NodeOf(state, instance) == nullptr) {
			return {};
		}

		// Collected upwards and written downwards, because a path reads from
		// the root and the tree only runs the other way.
		std::vector<core::Name> path;
		for (Entity walk = instance; walk != NULL_ENTITY; walk = ParentOf(state, walk)) {
			path.push_back(InstanceNameOf(state, walk));

			// Bounded by nothing else, so a tree that somehow held a cycle
			// would build a string until the process ran out of memory.
			// `SetParent` refuses to make one; this is the second lock.
			if (path.size() > MAXIMUM_DEPTH) {
				return {};
			}
		}

		std::string full;
		for (size_t index = path.size(); index > 0; index--) {
			if (!full.empty()) {
				full.push_back('.');
			}
			const core::Name step = path[index - 1];
			full.append(step.IsValid() ? step.Text() : std::string_view{});
		}
		return full;
	}

	bool IsDescendantOf(const StoreState &state, Entity instance, Entity ancestor) {
		for (Entity walk = instance; walk != NULL_ENTITY; walk = ParentOf(state, walk)) {
			if (walk == ancestor) {
				return true;
			}
		}
		return false;
	}

	bool SetParent(StoreState &state, Entity instance, Entity parent) {
		Hierarchy *node = MutableNodeOf(state, instance);
		if (node == nullptr) {
			return false;
		}
		if (parent != NULL_ENTITY && MutableNodeOf(state, parent) == nullptr) {
			return false;
		}

		// A cycle is not a wrong answer, it is a hang in every walk of the tree
		// — including the one that would destroy it.
		if (parent != NULL_ENTITY && IsDescendantOf(state, parent, instance)) {
			return false;
		}

		// **Re-parenting to the parent it already has does nothing**, and it has
		// to do nothing rather than do the same thing twice. Everything below
		// unlinks and then appends at the end, so a no-op assignment moved the
		// instance to the back of its own sibling list — and the sibling list
		// is the order `GetChildren()` returns, which replication and replay
		// both depend on agreeing across machines.
		//
		// The shape that finds it is ordinary Roblox code: a script that writes
		// `thing.Parent = holder` on a value that may or may not have changed,
		// or an editor that applies a drag by assigning the parent the row was
		// already under. Roblox's own assignment is a no-op here, so a game
		// written against it silently reorders on this engine and nothing says
		// why.
		if (node->Parent == parent) {
			return true;
		}

		// --- unlink from the old parent ---
		if (node->Parent != NULL_ENTITY) {
			Hierarchy *previous =
				node->PreviousSibling == NULL_ENTITY ? nullptr : MutableNodeOf(state, node->PreviousSibling);
			Hierarchy *next =
				node->NextSibling == NULL_ENTITY ? nullptr : MutableNodeOf(state, node->NextSibling);

			if (previous != nullptr) {
				previous->NextSibling = node->NextSibling;
			}
			if (next != nullptr) {
				next->PreviousSibling = node->PreviousSibling;
			}

			if (Hierarchy *old = MutableNodeOf(state, node->Parent); old != nullptr) {
				if (old->FirstChild == instance) {
					old->FirstChild = node->NextSibling;
				}
				if (old->LastChild == instance) {
					old->LastChild = node->PreviousSibling;
				}
			}

			// Re-read: every lookup above may have moved this row.
			node = MutableNodeOf(state, instance);
		}

		node->Parent = NULL_ENTITY;
		node->NextSibling = NULL_ENTITY;
		node->PreviousSibling = NULL_ENTITY;

		if (parent == NULL_ENTITY) {
			return true;
		}

		// --- link at the end of the new parent, so order is insertion order ---
		Hierarchy *host = MutableNodeOf(state, parent);

		// **A tail naming a freed row is repaired before it is written
		// through, not trusted.** `Store::Destroy` releases an entity without
		// touching the links that point *at* it — that unlink is what
		// `DestroyInstance` adds — so a parent outlives a destroyed child while
		// still naming it as `LastChild`. Every other lookup in this function
		// already tolerates a null; this one dereferenced it, and took the
		// process with it the next time anything parented into that same
		// parent.
		Entity last = host->LastChild;
		if (last != NULL_ENTITY && NodeOf(state, last) == nullptr) {
			last = RepairChildren(state, parent);
			// Re-read: the repair is a series of lookups, and any of them may
			// have moved this row.
			host = MutableNodeOf(state, parent);
		}

		if (last == NULL_ENTITY) {
			host->FirstChild = instance;
			host->LastChild = instance;
		} else {
			MutableNodeOf(state, last)->NextSibling = instance;
			MutableNodeOf(state, parent)->LastChild = instance;
		}

		node = MutableNodeOf(state, instance);
		node->Parent = parent;
		node->PreviousSibling = last;
		return true;
	}

	void DetachFromTree(StoreState &state, Entity instance) {
		// **`Assigned`, never `Of`.** This runs on every `Store::Destroy`,
		// including in a process that has not registered a single class yet —
		// and `Components::Of<Hierarchy>()` would *register* the type there,
		// under the compiler-spelled name, which the explicit `ecs.Hierarchy`
		// registration then aborts on. A type nothing has registered is a type
		// no row can be carrying, so an invalid id is the whole answer.
		const ComponentId hierarchy = Components::Assigned<Hierarchy>();
		if (!hierarchy.IsValid()) {
			return;
		}

		if (GetComponent(state, instance, hierarchy) == nullptr) {
			// Not an instance, so nothing in the tree names it. One component
			// lookup is the whole cost this adds to destroying a plain entity.
			return;
		}

		// **The children first, and re-rooted rather than destroyed.** Leaving
		// them pointing at a freed parent would not crash — `ParentOf` of a
		// dead handle is null — but it would make them invisible: `EachRoot`
		// asks for `Parent == NULL_ENTITY`, so a child whose parent is merely
		// *dead* is in the world, in the save file, and reachable from nothing.
		//
		// Collected before anything moves, because unlinking one rewrites the
		// sibling links the walk is standing on.
		std::vector<Entity> children;
		EachChild(state, instance, [&children](Entity child) { children.push_back(child); });

		for (const Entity child : children) {
			SetParent(state, child, NULL_ENTITY);
		}

		SetParent(state, instance, NULL_ENTITY);
	}

	void DestroyInstance(StoreState &state, Entity instance) {
		if (!IsEntityAlive(state, instance)) {
			return;
		}

		// Children collected before anything is destroyed, because destroying
		// one rewrites the sibling links the walk is standing on.
		std::vector<Entity> children;
		EachChild(state, instance, [&children](Entity child) { children.push_back(child); });

		for (const Entity child : children) {
			DestroyInstance(state, child);
		}

		SetParent(state, instance, NULL_ENTITY);
		DestroyEntity(state, instance);
	}

	namespace {
		// Copies a subtree, recording what became what.
		//
		// @param state  The world holding the source.
		// @param source The instance to copy.
		// @param made   Appended to as `{source, copy}` for every row copied.
		// @return The copy, or NULL_ENTITY when the source is not archivable.
		Entity CloneSubtree(StoreState &state, Entity source, std::vector<ClonedPair> &made) {
			if (!IsEntityAlive(state, source) || NodeOf(state, source) == nullptr) {
				return NULL_ENTITY;
			}

			// **Not archivable, not copied**, which is Roblox's rule and the
			// whole point of the flag: a marker an author puts on something
			// that a duplicate would break — a script's state holder, a debug
			// visualiser, anything that is one-of.
			if (GetComponent(state, source, Components::Of<NotArchivable>()) != nullptr) {
				return NULL_ENTITY;
			}

			const Entity copy = CloneOne(state, source);
			if (copy == NULL_ENTITY) {
				return NULL_ENTITY;
			}

			made.push_back(ClonedPair{source, copy});

			std::vector<Entity> children;
			EachChild(state, source, [&children](Entity child) { children.push_back(child); });

			for (const Entity child : children) {
				const Entity copied = CloneSubtree(state, child, made);
				if (copied != NULL_ENTITY) {
					SetParent(state, copied, copy);
				}
			}

			return copy;
		}
	}

	Entity CloneInstance(StoreState &state, Entity source, std::vector<ClonedPair> &made) {
		return CloneSubtree(state, source, made);
	}
}
